### DISCUSSION TITLE
How to assert one of many templates

### DISCUSSION THREAD

**Discussion by chlab** [helm-unittest/helm-unittest#613] [Q&A] [answered]
Let's say I want to assert that a helm chart defines a RoleBinding named `managed-admin-rb` and I don't care or know about any other RoleBindings the chart is creating.

If I write a test like:

```
tests:
  - it: 'Should have an admin RoleBinding'
    documentSelector:
      path: kind
      value: RoleBinding
      skipEmptyTemplates: true
      matchMany: true
    asserts:
      - equal:
          path: metadata.name
          value: managed-admin-rb
```

And the helm chart has these RoleBindings:

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewer-rb
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-admin-rb
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
```

The above test will fail because it will find the `viewer-rb` first:

```
 FAIL  RoleBindings	tests/test-rolebindings.yaml
	- Should have an admin RoleBinding

		- asserts[0] `equal` fail
			Template:	templates/rolebindings.yaml
			DocumentIndex:	0
			ValuesIndex:	0
			Path:	metadata.name
			Expected to equal:
				managed-admin-rb
			Actual:
				viewer-rb
```

We could rewrite the test to allow one of multiple names:

```
asserts:
      - matchRegex:
          path: metadata.name
          pattern: managed-admin-rb|viewer-rb
```

Then the test would pass, but I would need to know the name of all possible RoleBindings. Even if I did, I could only assert them all at once. I couldn't e.g. ensure that each of these required RoleBindings are defined: `managed-admin-rb|managed-inspect-rb`.

Is there a way to assert that (any) one of multiple matching documents fulfills my test?

**Comment by afalhambra-hivemq** [comment]
Have you tried using `documentIndex`:

```yaml
templates:
  - bindings.yml
...
tests:
  - it: 'Should have an admin RoleBinding'
    documentIndex: 1
    asserts:
      - equal:
          path: metadata.name
          value: managed-admin-rb
```

**Reply by chlab** [reply]
The problem with documentIndex is that you have to know the order in which the documents are defined. Relying on an arbitrary ordering would make a brittle test if the chart is restructured.

**Reply by afalhambra-hivemq** [reply]
but it is not an arbitrary ordering and rather deterministic, i.e. it will always be the same order unless you change the rendered manifest order in which case you will need to adapt your tests anyways, or?

**Reply by chlab** [reply]
We're a platform engineering team and our use case is testing developer teams' charts for certain best practices or requirements. I cannot have too many assumptions in how exactly their helm charts are structured.

**Reply by chlab** [reply]
Thanks anyway for your answer @afalhambra-hivemq !

**Reply by quintush** [reply]
Hello @chlab 

Within the documentSelector you can also use JsonPath, which also supports regex.

Take a look at the examples of the [documenteSelector](https://github.com/helm-unittest/helm-unittest/tree/main/test/data/v3/with-document-select)

Greetings,
@quintush

**Reply by chlab** [reply]
@quintush I recently found out, thanks. However, I'm not sure how it would help here. I tried this for example:

```
- it: 'Should have an admin RoleBinding'
    documentSelector:
      path: $[?(@.kind == 'RoleBinding')].metadata.name
      value: managed-admin-rb
    asserts:
      - hasDocuments:
        count: 1
```

This also fails if there are multiple RoleBindings defined:

```
 FAIL  RoleBindings	tests/test-rolebindings.yaml
	- Should have an admin RoleBinding

		- asserts[0] `hasDocuments` fail
			Template:	multiple-results/templates/rolebindings.yaml
			Expected documents count to be:
				0
			Actual:
				3
```

Which is curious, since the JSONPath selector should only match exactly one of my documents:

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-inspect-rb
roleRef:
  kind: Role
  name: inspect
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-admin-rb
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-view-rb
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
```
