### DISCUSSION TITLE
Parameterized tests

### DISCUSSION THREAD

**Discussion by chlab** [helm-unittest/helm-unittest#615] [Ideas]
To be able to define more complex tests, it would be useful to be able to define parameterized tests, as seen in other testing frameworks or technologies, e.g.

- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
- https://www.baeldung.com/parameterized-tests-junit-5
- https://github.com/wolever/parameterized

Here's how this could work from the point of view of writing the tests. Let's say we have a `Deployment` definition like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'foo-deployment'
  selector:
    matchLabels:
      app: 'foo'
spec:
  replicas: {{ .Values.deployment.replicaCount }}
```

and we want to ensure that there's a PodDisruptionBudget for each Deployment:

```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: 'foo-pdb'
spec:
  minAvailable: {{ sub .Values.deployment.replicaCount 1 }}
  selector:
    matchLabels:
      app: 'foo'
```

We could write a test like this:

```
tests:
  - it: should have a PodDisruptionBudget for each Deployment
    parameters:
      # each key defined here adds a "test dimension" to the execution, as well as a named variable containing the current value of the list
      # can be a constant or a jsonpath selector
      deployment: $[?(@.kind == 'Deployment')]
    # should fail if skipEmptyTemplates is false
    documentSelector:
      path: $[?(@.kind == 'PodDisruptionBudget')].selector.matchLabels.app
      value: $deployment.metadata.selector.matchLabels.app
    asserts:
      - greaterOrEqual:
          path: spec.minAvailable
          value: $deployment.spec.replicas - 1 # bonus: this could enable dynamic assertions
```

There would be a test result per `Deployment` found. The result set (combination of `parameters` + `documentSelector`) should be allowed to be empty.

Parametrized tests could also work will for simpler use cases, such as my question described [here](https://github.com/helm-unittest/helm-unittest/discussions/613). In this case, we could just define a constant with a list of RoleBindings we want to test for:

```
tests:
  - it: 'Should have required RoleBindings'
    parameters:
      roleBindingName: ['managed-admin-rb', 'managed-view-rb']
    documentSelector:
      path: kind
      value: RoleBinding
      matchMany: true
    asserts:
      - equal:
          path: metadata.name
          value: $roleBindingName
```

I would love to hear your thoughts on this @quintush. We increasingly rely on helm unittest at work and would be happy to take a stab at contributing this functionality if we can agree that this makes sense.

This would solve a few issues brought up in the past:
* https://github.com/helm-unittest/helm-unittest/issues/405
* https://github.com/helm-unittest/helm-unittest/issues/498
* https://github.com/helm-unittest/helm-unittest/issues/289 (probably)
* https://github.com/helm-unittest/helm-unittest/issues/222
