### DISCUSSION TITLE
documentSelector should support apiVersion

### DISCUSSION THREAD

**Discussion by chlab** [helm-unittest/helm-unittest#631] [Ideas]
Considering the following two templates:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
```

```yaml
apiVersion: myorg.tld/v1
kind: Service
metadata:
  name: dummy
```

The first is the K8s-native `Service`, the second a custom resource of my organization. When writing a test against one of these services, it should be possible to define an `apiVersion` so it's clear which `kind` I acutally mean.

```yaml
documentSelector:
  path: kind
  value: Service
  apiVersion: myorg.tld/v1
```

As a workaround, it's possible to use JSONPath:

```yaml
documentSelector:
  path: $[?(@.kind == 'Service')].apiVersion
  value: myorg.tld/v1
```

But this is not as readable as the native-support version and since `apiVersion` is an important part of the spec of a document, it should be supported by the documentSelector imho.

We would be willing to provide a PR for this if this proposal is accepted.
