### DISCUSSION TITLE
Define a minimum expected version of the plugin per testsuite

### DISCUSSION THREAD

**Discussion by chlab** [helm-unittest/helm-unittest#632] [Ideas]
Some tests will fail if the client is running an older version of the plugin (see example below). In our case, we have no control over the version of helm unittest running on the developers machines, but we distribute a library of tests to test their projects against. For this, it would be helpful to be able to define a minimum expected version of the plugin in the testsuite, e.g.:

```yaml
suite: Test RBAC definitions
minVersion: 0.8.1
templates:
  - templates/*.y*ml
tests:
  - it: 'Should create a rolebinding for admin role'
    documentSelector:
      path: metadata.name
      value: managed-admin-rb
      skipEmptyTemplates: true
    asserts:
      - hasDocuments:
          count: 1
          filterAware: true # this will fail if client is running 0.8.0 and has multiple role bindings
```

If the plugin version is lower, the test would fail with a helpful error message:

```
- Test RBAC definitions fail
    Template:	templates/rbac.yaml
	Expected version:
		0.8.1
	Actual:
		0.8.0
```

We would be willing to provide a PR for this if this proposal is accepted.
