### ISSUE TITLE
asserts[0] `isKind` fail

### ISSUE THREAD

**Issue by bruno-novo-freshbooks** [helm-unittest/helm-unittest#119]
Hello everyone,

Which kind of manifest's helm-unittest support right now? I tried to create a suite for HPA, Ingress, PodDisruptionBudget, using this same test structure:

```
suite: test ingress
templates:
  - ingress.yaml
tests:
  - it: should work
    asserts:
      - isKind:
          of: Ingress

```
But got this error about the template. Really not sure if the main problem could be my template for it.
   
I was able to create and passing test with `Deployment, Service, Congfimap and Service Account`

Thanks a lot

**Comment by quintush** [comment]
Hello @bruno-novo-freshbooks,

All kinds are supported, even custom api's.

Can you send an example of the ingress.yaml?

My first thought would be that the ingress.yaml is not rendered at all.
Most of the default helm templates don't render the ingess.yaml, without setting a value like:
ingress.enabled: true

Greetings,
@quintush

**Comment by bruno-novo-freshbooks** [comment]
Hello @quintush 

You rock man, that's the main problem. Totally forgot to enable the manifest. The final result is this:

```
suite: test ingress
templates:
  - ingress.yaml
tests:
  - it: should work
    set:
      ingress.enabled: true
    asserts:
      - isKind:
          of: Ingress
```

Thank you very much for the quick response and for the help.
