### ISSUE TITLE
test: set and values cannot be used simultaneously

### ISSUE THREAD

**Issue by mederel** [helm-unittest/helm-unittest#124]
I have a reproducer here: 
[helm-unittest-reproducer-global-double-setting.zip](https://github.com/helm-unittest/helm-unittest/files/10853886/helm-unittest-reproducer-global-double-setting.zip)

It boils down to having a required value global.app that's not set by default:

values.yaml

```yaml
global:
  app:
```

template:

```
metadata:
  name: {{ .Values.global.app | required "global.app is mandatory" }}
```

Hence to help out in the writing of tests a requiredValues.yaml is created on the side to set it:

tests/values/requiredValues.yaml

```
global:
  app: my-name
```

But then in a test we write the following:

```yaml
templates:
  - templates/deployment.yaml
tests:
  - it: reproducer test
    values:
      - values/requiredValues.yaml
    set:
      global:
        containerName: blibli
    asserts:
      - equal:
          path: spec.template.spec.containers[0].name
          value: blibli
```

This test fails with: 

```
 FAIL   helm-unittest-reproducer-global-double-setting/tests/deployment_test.yaml
        - reproducer test
                Error: execution error at (helm-unittest-reproducer-global-double-setting/templates/deployment.yaml:4:32): global.app is mandatory
```

It looks like the set `global.containerName` has overridden entirely the requiredValues.yaml setting.

__Important: happens since helm unittest 0.3.0__
