### ISSUE TITLE
test: set/values support inline yaml

### ISSUE THREAD

**Issue by copa2** [helm-unittest/helm-unittest#126]
Hi @quintush 

It would be nice when we can define fixtures inline in yaml file and then reference the values in the test.
This is currently not working as it merges the sets not together. 

```yaml
fixtures:
  required: &required-values
    app:
      image: my-image
      cron: 
        schedule: "*/1 * * * *"

tests:
  - it: Basic test
    set:
      <<: *required-values
      app:
        cron:
          backoffLimit: 3
    asserts:
      - matchSnapshot: {}
```
It would be nice if this would be merged to: 
```yaml
app:
  image: my-image
  cron: 
    backoffLimit: 3
    schedule: "*/1 * * * *"
```
Later definitions should overwrite previous definitions (like in values).

I see this is hard to detect where a new files begins for merging. Probably introduce 'sets' key like in values where we can provide list of values, or allow in values to reference inline "yaml" instead of referencing a file.

By the way thanks for taking over this library and provide usefull enhancements.

**Comment by copa2** [comment]
I used it wrongly. With flat structure like on CLI it works as expected.

```yaml
fixtures:
  required: &required-values
    app.image: my-image
    app.cron.schedule: "*/1 * * * *"

tests:
  - it: Basic test
    set:
      <<: *required-values
      app.cron.backoffLimit: 3
    asserts:
      - matchSnapshot: {}
```
