### ISSUE TITLE
Test fails with multiple objects in one template

### ISSUE THREAD

**Issue by 2ban** [helm-unittest/helm-unittest#128]
Hi, we have multiple objects defined in single template file and in this case tests are failing:
template
```
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: app1 
---
apiVersion: v1
kind: Secret
metadata:
  name: any-secret
data:
  username: {{ .Values.credentials.username }}
  password: {{ .Values.credentials.password }}
type: Opaque
```
test.yaml
```
suite: test services
templates:
  - deployment_and_services.yaml
tests:
  - it: should work
    values:
      - ../values.yaml
    asserts:
      - equal:
          path: spec.type
          value: "ClusterIP"
```
values.yaml
```
service:
  type: ClusterIP
  port: 80

credentials:
  username: foo
  password: bar
```
The error:
```
### Chart [ mychart ] .

 FAIL  test services    tests/services_test.yaml
        - should work

                - asserts[0] `equal` fail
                        Template:       mychart/templates/secret_and_service.yaml
                        DocumentIndex:  1
                        Error:
                                can't get ["type"] from a non map type:
                                null
```

The test works if we delete Secret object or move it to other file. It also works with plugin https://github.com/vbehar/helm3-unittest
