### ISSUE TITLE
Regression: isEmpty validation is failing on a null object

### ISSUE THREAD

**Issue by jcogilvie** [helm-unittest/helm-unittest#134]
I have this test:

```
  - it: does not supply topology spread constraints when the default flag is disabled
    set:
      commitSha: 12345
      useDefaultTopologySpread: false
    asserts:
      - isKind:
          of: Deployment
      - isEmpty:
          path: spec.template.spec.topologySpreadConstraints
```

It used to pass.  After updating helm-unittest from 0.2.11 to 0.3.0 (or 0.3.1), it fails.

Relevant chart chunk:

```
  {{- if .Values.useDefaultTopologySpread }}
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        {{ include "lib.selectorLabels" . | nindent 8 }}
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        {{ include "lib.selectorLabels" . | nindent 8 }}
  {{- else }}
  {{- with .Values.topologySpreadConstraints }}
  topologySpreadConstraints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

Relevant values excerpt:

```
useDefaultTopologySpread: false
topologySpreadConstraints: {}
```

According to `helm template`, in the test configuration, `topologySpreadConstraints` ends up a null object.  However, the test fails like so:

```
 FAIL  test scheduling configuration	tests/scheduling_test.yaml
	- does not supply topology spread constraints when the default flag is disabled

		- asserts[1] `isEmpty` fail
			Template:	my-service/templates/deployment.yaml
			DocumentIndex:	0
			Error:
				unknown path spec.template.spec.topologySpreadConstraints
```

This failure occurs for another test in the same way, too.  Changing to `isNull` works.
