### ISSUE TITLE
Tests not rendering when using $.Files.Get

### ISSUE THREAD

**Issue by erik-carlson** [helm-unittest/helm-unittest#135]
Consider template template.yaml:
`{{ $.Files.Get "files/foo.yaml" }}`

files/foo.yaml:
`foo: bar`

and tests/foo_test.yaml:
```
templates:
  - template.yaml
 tests:
  - asserts:
    - equal:
      path: foo
      value: bar
```

using the 0.3.1 version of the plugin the test fails. Using version 0.2.11 of quintush fork passes.

If `documentIndex: 0` is added to the test, 0.3.1 fails with "documentIndex 0 out of range", so it seems like the `$.Files.Get` is not working.

I'm using helm version 3.11.1.

**Comment by quintush** [comment]
Hello @erik-carlson,

Thanks for the feedback.
Identified the root cause, as in the new version i'm filtering the templates and filtered all non-template files resulting in the error.

Will fix this and also setup a test scenario which uses external files, to prevent regression in the future.

Greetings,
@quintush

**Comment by quintush** [comment]
Hello @erik-carlson,

Created a fix and included validation to verify the behvaiour.

Greetings,
@quintush

**Comment by stepbeta** [comment]
Hi, I'm finding this doesn't work yet.

I've got the following:

```yaml
# template: base.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "my-role"
rules:
## initially I had the file path as a variable, but I hardcoded it to simplify, and it fails too
{{ $.Files.Get "tests/values/test.yaml" | indent 2 }}

# values: values/test.yaml
---
- api_groups: ["*"]
  resources: ["*"]
  verbs: ["*"]
```

Test definition:

```yaml
---
suite: Base role tests
templates:
  - base.yaml
tests:
  - it: Should create a ClusterRole with the right rules
    values:
      - values/test.yaml
    documentIndex: 0
    asserts:
      - equal:
          path: rules
          value:
            - api_groups: ["*"]
              resources: ["*"]
              verbs: ["*"]
```

Test result:

```sh
### Chart [ my-chart ] .
FAIL  Base role tests  tests\role_test.yaml
    - Should create a ClusterRole with the right rules
        - asserts[0] `equal` fail
            Template:       my-chart/templates/base.yaml
            DocumentIndex:  0
            Path:   rules
            Expected to equal:
                - api_groups:
                    - '*'
                resources:
                    - '*'
                verbs:
                    - '*'
            Actual:
                null
            Diff:
                --- Expected
                +++ Actual
                @@ -1,7 +1,2 @@
                -- api_groups:
                -    - '*'
                -  resources:
                -    - '*'
                -  verbs:
                -    - '*'
                +null
```

I don't see anything wrong with my setup, would you have any insights? I'm using v0.3.3:

```sh
$> helm plugin list
NAME            VERSION DESCRIPTION
unittest        0.3.3   Unit test for helm chart in YAML with ease to keep your chart functional and robust.
```
