### ISSUE TITLE
Assertion `containsDocument` isn't working correctly with `not: true`

### ISSUE THREAD

**Issue by jcogilvie** [helm-unittest/helm-unittest#145]
version 0.3.2

Test `autoscaling_test.yaml`: 

```yaml
  - it: has no ScaledObject when autoscaling is disabled (default)
    set:
      autoscaling:
        enabled: false
    asserts:
      - containsDocument:
          kind: ScaledObject
          apiVersion: keda.sh/v1alpha1
        # invert the assertion
        not: true
```

Template:

```yaml
{{- if .Values.autoscaling.enabled }}
{{- with .Values.autoscaling }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
[object definition here, but it's disabled]
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
[another object, but again, the whole file is disabled]
{{- end -}}
{{- end -}}
```

Result:
```
 FAIL  test autoscaling configuration   tests/autoscaling_test.yaml
        - has no ScaledObject when autoscaling is disabled (default)

                - asserts[0] NOT `containsDocument` fail
                        Template:       terminus-service/templates/autoscaling.yaml
                        DocumentIndex:  0
                        Expected NOT to contain document:
                                Kind = ScaledObject, apiVersion = keda.sh/v1alpha1
```

Expectation:  should pass due to the file being rendered empty

Further information:

This is the same failure I receive if I remove the `not: true`.  Here that is, for completeness:

```
 FAIL  test autoscaling configuration   tests/autoscaling_test.yaml
        - has no ScaledObject when autoscaling is disabled (default)

                - asserts[0] `containsDocument` fail
                        Template:       terminus-service/templates/autoscaling.yaml
                        DocumentIndex:  0
                        Expected to contain document:
                                Kind = ScaledObject, apiVersion = keda.sh/v1alpha1
```
