### ISSUE TITLE
Path not found if the key contains a dot

### ISSUE THREAD

**Issue by RetGal** [helm-unittest/helm-unittest#148]
```
asserts:
  - equal:
      path: data.hakuna.matata
      value: aGFrdW5hIG1hdGF0YQ
```
fails with: `unknown path data.hakuna.matata`

```
data:
  hakuna.matata: aGFrdW5hIG1hdGF0YQ
```
