### ISSUE TITLE
Add flag to exclude certain charts from unit testing.

### ISSUE THREAD

**Issue by RyanW8** [helm-unittest/helm-unittest#160]
We currently have a monorepo hosting a variety of our internal helm charts. We currently have the following GH action setup:
```
name: "ci/unit-tests"

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: unit-tests
        uses: d3adb5/helm-unittest-action@v2.2
        with:
          flags: -o helm-unittest-output.xml -t junit
```

This works nicely however one of our charts depends on a chart hosted in our private artifact store. Ideally we'd host the GH runners ourselves in order to access the private infra, but in the mean time we'd like to be able to ignore certain charts, perhaps a flag e.g. `--exclude-charts chart1,chart2`
