### ISSUE TITLE
Escape not possible anymore

### ISSUE THREAD

**Issue by khauser** [helm-unittest/helm-unittest#165]
We do have some problems in our unittest execution in connection with ConfigMaps.
In an older version (e.g. 0.2.8) we were able to type: `data.myFile\.xml` and could test the existence of data within a configmap. Now in 0.3.2 and 0.3.3 we get `unknown path` when trying so.

Here are some files to understand the problem:
templates/myFile-xml-cm.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: testConfigMap
data:
  myFile.xml:  |-
    <?xml version="1.0"?>
    <myTag />
```

unittest.yaml
```
    asserts:
      # unfortunatelly the complex content can not be checked
      - isNotEmpty:
          path: data.myFile\.xml
```

Error:
```
 FAIL  test correctness of replication related values   charts/myChart/tests/myFile_xml_test.yaml
        - myFile-xml-cm default values

                - asserts[0] `isNotEmpty` fail
                        Template:       templates/myFile-xml-cm.yaml
                        DocumentIndex:  0
                        Error:
                                unknown path data.myFile\.xml
```

Is there an alternative way or is this a bug?

Best,
Karsten
