### ISSUE TITLE
`containsDocument`: `name` has no effect?

### ISSUE THREAD

**Issue by pat-s** [helm-unittest/helm-unittest#167]
It doesn't matter what is set as `name`, the test never passed. The output (and the documentation at https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md#assertion-types) indicate that `name` is possibly ignored/not used?

```
  - it: title
    template: templates/app/svc.yaml
    set:
      service.ssh.enabled: true
    asserts:
      - containsDocument:
          kind: Service
          apiVersion: v1
          name: <service name>-ssh
```

```
        - <name>
                - asserts[0] `containsDocument` fail
                        Template:       app/templates/app/svc.yaml
                        DocumentIndex:  0
                        Expected to contain document:
                                Kind = Service, apiVersion = v1
```
