### ISSUE TITLE
Assertion type `isNullOrEmpty` is invalid

### ISSUE THREAD

**Issue by dils0n** [helm-unittest/helm-unittest#168]
Hi, I'm trying to run helmunittest/helm-unittest:3.11.1-0.3.0 with my unittests and I got error "Assertion type `isNullOrEmpty` is invalid" isEmpty seems doesn't work either. Indeed isNull assertion is passed, could you please check? 

I got this values 

      {{- if .Values.hostAliases }}
      hostAliases: {{ toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      
  and this test 
  
```
  tests:
  - it: hostAliases missing
    set:
      hostAliases: null
    asserts:
      - isKind:
          of: Deployment
      - isNull:
          path: spec.template.spec.hostAliases
  - it: default hostAliases
    asserts:
      - isNullOrEmpty:
          path: spec.template.spec.hostAliases
```
