### ISSUE TITLE
Add flag to exclude certain templates from testing

### ISSUE THREAD

**Issue by BogdanSorlea** [helm-unittest/helm-unittest#169]
Hey,

It would be nice to be able to list the templates a test should be run against by assuming all and then excluding selectively.
This is particularly relevant as mechanism to avoid the unfortunate scenario of new template being added to chart, against which the test with ~(negative)~ assumptions should run, but forgetting to have it added to the list of templates (list because some templates are not to be tested with those ~(negative)~ assumptions). Would be nice to have a smart mechanism like this that would allow for such a scenario to not cause a problem (i.e. by forgetting to add the line and then missing it during code review).

current working example
```
suite: test all kubernetes resources
tests:
  - it: should not have component label on non-deployment, non-jobs, non-sg-policy resources
    templates:
      - configmaps.yaml
      - ingresses.yaml
      - services.yaml
    asserts:
      - notExists:
          path: metadata.labels.component
```

If I add a hpa.yaml and I don't add it to the list of templates, if the hpa.yaml has a metadata.labels.component then it's not compliant with the expectations and can lead to inconsistencies and non-compliance.

the code that would address this could look like:
```
suite: test all kubernetes resources
tests:
  - it: should not have component label on non-deployment, non-jobs, non-sg-policy resources
    templates:
      - *
    templateExclude:
      - deployments.yaml
      - jobs.yaml
      - sg-policy.yaml
    asserts:
      - notExists:
          path: metadata.labels.component
```

Hope the example above is clear enough.

Similar concept to https://github.com/helm-unittest/helm-unittest/issues/160 - but definitely not the same

Side-quest: the docs [here](https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md#:~:text=which%20are%20prefixed%20with%20and) are including some omission and therefore I'm not sure if the wildcard mentioned in that paragraph exists and manifests itself similar to the `*` I suggest in my code just above. Would be good to clarify what those wildcards are / how to use them (didn't immediately see examples either). And ofc, to consider implementing wildcards like `*` for `templates` list if they don't exist already.
