### ISSUE TITLE
Simplify chart library testing

### ISSUE THREAD

**Issue by eshepelyuk** [helm-unittest/helm-unittest#171]
Library charts don't generate any input, so it is not possible to unittest them directly. Library charts can only be tested on a fake chart that uses the library chart as a dependency.

This project could simplify a developers' lives by hiding this, i.e. detecting that current chart is a library and creating a fake chart behind the scene, with the library chart as dependency.

Copy of https://github.com/quintush/helm-unittest/issues/34

**Comment by quintush** [comment]
Hello @eshepelyuk,

I'm currently investigating the possibility to make an assertion which can render the go template definitions
This assertion can than also be used to validate library charts (as they also contain defintions)

Greetings,
@quintush

**Comment by maverick1872** [comment]
An MVP of this might be to allow us to just define a resource template that is specific to the test. This would mean `helm-unittest` doesn't have to concern itself with generating a fake chart per-se.

Directory structure would look something along the lines of the following:
```
.
├── templates/
│   └── _labels.yaml                   <- Library template for labels
└── tests/                             <- Tests for the Library chart
    ├── __snapshots__/                 <- Generated Snapshots
    ├── templates/                     <- Templates defined purely for testing library template
    |   └── example_deployment.yaml    <- Templates defined purely for testing library template
    ├── values/                        <- Values files for tests
    └── labels_test.yaml               <- Test definition for lables
```

**Comment by JuryA** [comment]
I'm using this workaround to test my **Named Templates** with **unittest**:

In my `NOTES.txt` I have this:

```go
{{- if index .Values "__test" -}}
{{- tpl (index .Values "__test") $ -}}
{{- end -}}
```

My test looks like this:

```yaml
  - it: template [jdbc.injectTpl] should render "VolumeMount" TEMPLATE with LEVEL "Item" if TEMPLATE is set to "VolumeMount" and LEVEL is set to "Item"
    set:
      __test: '{{ include "jdbc.injectTpl" (dict "ROOT" $ "TEMPLATE" "VolumeMount" "LEVEL" "Item") }}'
    asserts:
      - equalRaw:
          value: '{"mountPath":"/path/to/inject","name":"jdbc-drivers"}'
```

**Comment by hrivera-ntap** [comment]
Ideally helm-unittest would support library charts natively.

In the meantime, I've settled on a temporary workaround that doesn't feel too icky. I created a mock application chart in the same repository as the library chart that contains the unit tests and the named template files.

Then inside the `charts/` directory of the mock chart, I created a relative symlink to the library chart so that the mock chart uses the library chart as a dependency. 

You can then invoke helm unittest against the mock application chart in your CI to exercise the library chart's functions more easily.


When invoking helm unittest you'll see something like:

```
2024/03/03 16:01:05 found symbolic link in path: /mock-chart/charts/ resolves to /library-chart. Contents of linked file included and used
```

**Comment by G-Novotny** [comment]
> I'm using this workaround to test my **Named Templates** with **unittest**:
> 
> In my `NOTES.txt` I have this:
> 
> ```go
> {{- if index .Values "__test" -}}
> {{- tpl (index .Values "__test") $ -}}
> {{- end -}}
> ```
> 
> My test looks like this:
> 
> ```yaml
>   - it: template [jdbc.injectTpl] should render "VolumeMount" TEMPLATE with LEVEL "Item" if TEMPLATE is set to "VolumeMount" and LEVEL is set to "Item"
>     set:
>       __test: '{{ include "jdbc.injectTpl" (dict "ROOT" $ "TEMPLATE" "VolumeMount" "LEVEL" "Item") }}'
>     asserts:
>       - equalRaw:
>           value: '{"mountPath":"/path/to/inject","name":"jdbc-drivers"}'
> ```

@JuryA can you please elaborate a bit more on that?
When trying to replicate your approach for testing helm library charts I recieve the error `template "openliberty/templates/NOTES.txt" not exists or not selected in test suite`.

Please find below my NOTES.txt (located inside the templates folder of my library chart), the unittest, the named template as well as the shell output.

./templates/NOTES.txt:
```
{{- if index .Values "__test" -}}
{{- tpl (index .Values "__test") $ -}}
{{- end -}}
```

./tests/confugmap_test.yaml
```yaml
suite: test suite for openliberty applicationConfig template
templates:
  - NOTES.txt
tests:
  - it: should render ConfigMap with provided applicationConfig values
    set:
      __test: '{{ include "openliberty.applicationConfig.tpl" . }}'
      applicationConfig:
        key1: value1
        key2: value2
    asserts:
      - matchRegexRaw:
          pattern: ConfigMap
      - matchRegexRaw:
          pattern: "^.*-configmap$"
      - matchRegexRaw:
          pattern: "^value1$"
      - matchRegexRaw:
          pattern: "^value2$"
```


./templates/_configmap.yaml
```yaml
{{- define "openliberty.applicationConfig.tpl" -}}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openliberty.fullname" . }}-configmap
data:
  {{- with .Values.applicationConfig }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
```
