### ISSUE TITLE
Syntax errors and typos in the tests fail open

### ISSUE THREAD

**Issue by m-ildefons** [helm-unittest/helm-unittest#178]
# Problem

Syntax errors, typos and other mistakes in a test or testsuite fail open.

For example, consider the following test:
```
suite: foobar
templates:
  - deployment.yaml
tests:
  - it: should not pass
    assert:
      - hasDocuments:
          count: 0
```
Assuming that `deployment.yaml` does contain some yaml document, this test should by all accounts not pass, but it does. The reason it passes is that the key `assert` is wrong, it's missing an `s` and should be `asserts`.
This and similar hard to spot kinds of errors in the test suites should cause the respective unit test to fail.

# Actual Result

Tests pass

# Expected Result

Test "should not pass" in the suite "foobar" should fail.

**Comment by quintush** [comment]
Hello @m-ildefons,

Thanks for the feedback.
I will add additional checks in parsing the testSuite file.

Greetings,
@quintush

**Comment by m-ildefons** [comment]
Hey @quintush ,

thanks for looking into this. I've played around with the command line options a bit more and it seems like the `--strict` option already suffices to solve the issue I was seeing.
I think it should be on by default.

While testing out the strict option, I found another corner case where having `--strict` on improves behavior of the plugin:

If you have the following typo: `template` instead of `templates`:
```yaml
---
suite: Foobar
template:
  - foobar.yaml
tests:

  - it: foobar
    asserts:

      - hasDocuments:
          count: 1
        templates:
          - foobar.yaml
```
With the strict option enabled, it will fail the test suite due to the typo. With the strict option disabled, it will execute the test suite, but will also try to fill in _all_ templates. This can cause confusing test failures when there are other templates than `foobar.yaml` that for a value in the `values.yaml` to be provided via a mechanism like:
```yaml
{{- if (empty .Values.requiredValue) }}
{{- fail "Please provide requiredValue" }}
{{- end }}
```
This is because in this case filling out _all_ templates without providing that value will cause the templating process to fail.
