### ISSUE TITLE
documentIndex is brittle

### ISSUE THREAD

**Issue by hansbogert** [helm-unittest/helm-unittest#179]
Our tests include template files which produce yaml files with many documents, in which the ordering might often change.

Is there a way to select a document with a yaml-path or something like that?

For example, we now have something like this:

```yaml
suite: prometheus
templates:
  - addons/default-values.yaml
tests:
  - it: X
    set:
      prometheusOperator.enabled: true
    values: [ generic-x.yaml ]
    documentIndex: 11 # Prometheus. Index-based is pretty brittle if the ordering ever changes
    asserts:
      - isKind:
          of: ConfigMap
      - matchSnapshot: {}
  - it: non-x
    values: [ generic-y.yaml ]
    documentIndex: 8 # Prometheus. Index-based is pretty brittle if the ordering ever changes
    asserts:
      - isKind:
          of: ConfigMap
      - matchSnapshot: {}

```

This would immediately break if our addons/default-values template will output extra ConfigMaps due to our base values being changed.

I'd expect something like 

```yaml
suite: prometheus
templates:
  - addons/default-values.yaml
tests:
  - it: X
    set:
      prometheusOperator.enabled: true
    values: [ generic-x.yaml ]
    documentSelector:
      - hasName: prometheus-operator-default-values
      - path: something.else
           is: "toCheck"
    asserts:
      - isKind:
          of: ConfigMap
      - matchSnapshot: {}
...

```

If there isn't an alternative to selecting a document other than its numerical index, are the maintainers open to have this implemented?
