### ISSUE TITLE
Assertion `contains` should consider also dictionary structures?

### ISSUE THREAD

**Issue by lucasvc** [helm-unittest/helm-unittest#180]
I started to use this, and I was trying to verify the following `ConfigMap` template,

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fancy-config-map
  labels: {}
  annotations: {}
data:
  fixed: from a map
  {{ .Values.environmentVariables | toYaml | nindent 2 }}
```

The `data` entry contains other entries, but not in array form but in dictionary.
I was expecting the following test to pass,

```
suite: test configure environment variables
templates:
  - templates/config-env.yaml
tests:
  - it: config-env should render and default values
    set:
      environmentVariables:
        VARIABLE_TO_ENV: should be added
    asserts:
      - isKind:
          of: ConfigMap
      - hasDocuments:
          count: 1
      - contains:
          path: data
          content:
            fixed: from a map
            VARIABLE_TO_ENV: should be added
          count: 2
```

but resulting in failed

```
 FAIL  test configure environment variables     myelm/tests/config-env_test.yaml
        - config-env should render and default values

                - asserts[2] `contains` fail
                        Template:       myelm/templates/config-env.yaml
                        DocumentIndex:  0
                        Error:
                                expect 'data' to be an array, got:
                                VARIABLE_TO_ENV: should be added
                                fixed: from a map
```

It is expected that `contains` only to be working with arrays and not also with dictionaries?

**Comment by lucasvc** [comment]
Doing more tests on my helm chart, I have realised that seems that can't be checked multiple elements with contains:

```
apiVersion: v1
kind: PodMonitor
metadata:
  name: fancy-monitor
  labels: {}
spec:
  selector:
    matchLabels: {}
  podTargetLabels:
    - application
    - workload-type
```

```
suite: test pod monitorization configuration
templates:
  - templates/podimonitori.yaml
tests:
  - it: pod monitor should render and default values
    asserts:
    - isKind:
        of: PodMonitor
    - hasDocuments:
        count: 1
    - lengthEqual:
        path: spec.podTargetLabels
        count: 2
    - contains:
        path: spec.podTargetLabels
        content:
          - application
          - workload-type
```

result in a "bad" expected array,

```
 FAIL  test pod monitorization configuration    myelm/tests/podmonitor_test.yaml
        - pod monitor should render and default values

                - asserts[3] `contains` fail
                        Template:       myelm/templates/podmonitor.yaml
                        DocumentIndex:  0
                        Path:   spec.podTargetLabels
                        Expected to contain:
                                - - application
                                  - workload-type
                        Actual:
                                - application
                                - workload-type
```
