### ISSUE TITLE
Intermittent test failures when using `failedTemplate`

### ISSUE THREAD

**Issue by jcogilvie** [helm-unittest/helm-unittest#183]
I have the following defined in my chart:

```
{{- $_ := .Values.ingress.rules | required "A set of .Values.ingress.rules is required" -}}
```

When I test for a failure of the required item, like so:

```
globallyRequiredValues: &globallyRequiredValues
  commitSha: 12345
  environment: foo
  codeRepo: https://github.com/myco/helm-charts
  ingress:
    rules:
      - host: "foo.com" # not under test here
  resources: {}

suite: test service defaults
tests:
  - it: requires ingress rules
    set:
      <<: *globallyRequiredValues
      ingress.rules: ~
    asserts:
      - failedTemplate:
          errorMessage: A set of .Values.ingress.rules is required
```

It works about 75% of the time.  The other 25% of the time, it fails with:

```
 FAIL  test service defaults	tests/defaults_test.yaml
	- requires ingress rules

		- asserts[0] `failedTemplate` fail
			Error: rendered manifest is empty
```

This is likely related to the same refactoring work you are already doing, but I wanted to make sure to call it out in an issue.

**Comment by quintush** [comment]
Hello @jcogilvie,

Thanks for the feedback.
This issue still applies in one of my own tests, but it is harder to tackle.

See my previous comment on #182, will try the enable more debug statements to get more knowledge on the inconsistent ordering of multiple documents.

Greetings,
@quintush

**Comment by jcogilvie** [comment]
Hi @quintush,

I have another similar case that seems to be permanently failing.  

```bash
 FAIL  test service defaults	tests/defaults_test.yaml
	- requires a slackAlertChannel

		- asserts[0] `failedTemplate` fail
			Error: Invalid rendering: %!s(<nil>)
```

I use a minimal values file shared between tests to pass validation of all my other required properties, so by default, I set `slackAlertChannel` to a value.  For this test, I (un)set it to null to force validation to fail and catch the error:

Test:
```yaml
  - it: requires a slackAlertChannel
    set:
      slackAlertChannel: ~
    asserts:
      - failedTemplate:
          errorMessage: A valid .Values.slackAlertChannel is required
```

Failing template (from a partial):

```yaml
{{- define "lib.slackChannel" -}}
{{ print ((coalesce .Values.slackAlertChannel (.Values.datadog.monitors).slackAlertChannel) | required "A valid .Values.slackAlertChannel is required") }}
{{- end -}}
```

Oddly, if I unset the value directly in my minimal values file so that none of the tests are using it, all my other tests fail with the expected error message.

**Comment by ivankatliarchuk** [comment]
The second example is not correct. Your minimal values are
```yml
slackAlertChannel: ~
datadog:
  monitors:
```

Basically the expression `(.Values.datadog.monitors.)` will evaluate to `nil pointer evaluating interface {}.monitors` if the minival provided values are

```yml
slackAlertChannel: ~
```

**Comment by ivankatliarchuk** [comment]
Would be nice to have a full example with unitest version that is used.
I have created a repository to reproduce an initial [issue](https://github.com/ik-workshop/helm-unittests-issues/tree/master/issue-183)

So the template is
```yml
---
{{- $_ := .Values.ingress.rules | required "A set of .Values.ingress.rules is required" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    rules: {{ .Values.ingress.rules  }}
    type-of: {{ typeOf .Values.ingress.rules }}
spec:
  ingressClassName: nginx-example
```

the test

```yml
---
globallyRequiredValues: &globallyRequiredValues
  commitSha: 12345
  environment: foo
  codeRepo: https://github.com/myco/helm-charts
  ingress:
    rules:
      - host: "foo.com" # not under test here
  resources: {}

suite: "test paradox"
templates:
  - templates/ingress.yaml
tests:
  - it: Should catch error when "ingress.rules" e.g. tilde ~
    set:
      <<: *globallyRequiredValues
      ingress.rules: ~
    asserts:
      - failedTemplate:
          errorMessage: A set of .Values.ingress.rules is required
```

I manage to catch a failure

![Screenshot 2024-01-13 at 14 02 46](https://github.com/helm-unittest/helm-unittest/assets/5395690/3954244d-b16b-4eeb-b08b-c503fe9c3444)

Interesting enough, the issue is not consistent. It either fail or success.

If in the test instead of 
```
set:
    <<: *globallyRequiredValues
    ingress.rules: ~
```

To set 
```
set:
      <<: *globallyRequiredValues
      ingress:
        rules: ~
```

The error completely disappeared, which means there seems to be an issue with the provided YAML library. 

Interesting enough, I have tried `helm template` for the same, and there was a consistent failure

![Screenshot 2024-01-13 at 14 04 34](https://github.com/helm-unittest/helm-unittest/assets/5395690/5c1fa9c8-ed94-4bd6-af03-a0f71d983969)

But everything fine if when run `helm tempalte` with `--set ingress.rules=abra-cadabra-v2`

```sh
	helm template chart $(folder) \
		--output-dir output -n default \
		-f $(folder)/values.yaml \
		--set ingress.rules=abra-cadabra-v2 \
		--debug
```

**Comment by ivankatliarchuk** [comment]
To clarify a bit more. This is what happening. The framework is trying to interpret

```yml
ingress.routes: ~
```

Sometimes as

```json
{
  "ingress": { "routes": "~" }
}
```

And sometimes as

```json
{
  "ingress.routes": "~"
}
```

No sure why interpretation is not consistent. But with option 1 - the helm trow a validation error, as expected.
For the second e.g. `ngress.routes`, there is a nill a helm trows exception ` did not find expected ',' or ']'`
``

**Comment by ivankatliarchuk** [comment]
slightly tweaked the test, to catch `nil
```yaml
globallyRequiredValues: &globallyRequiredValues
  commitSha: 12345
  environment: foo
  codeRepo: https://github.com/myco/helm-charts
  ingress:
    rules: hello-world
  resources: {}

suite: "test paradox"
templates:
  - templates/ingress.yaml
tests:
  - it: Should catch error when "ingress.rules" e.g. tilde ~
    set:
      <<: *globallyRequiredValues
      ingress.rules: ~
    asserts:
      - failedTemplate:
          errorMessage: A set of .Values.ingress.rules is required
```

output
```
assertions: line 46
&{ -1 <nil> false failedTemplate 0xc0005a4120 false false [chart/templates/ingress.yaml]}
---
 FAIL  test paradox	issue-183/tests/ingress-nill_test.yaml
	- Should catch error when "ingress.rules" e.g. tilde ~

		- asserts[0] `failedTemplate` fail
			Error: Invalid rendering: %!s(<nil>)
```

**Comment by ivankatliarchuk** [comment]
To clarify a bit more. This is what happening. The framework is trying to interpret

```yml
ingress.routes: ~
```

Sometimes as

```json
{
  "ingress": { "routes": "~" }
}
```

And sometimes as

```json
{
  "ingress.routes": "~"
}
```

No sure why interpretation is not consistent. But with option 1 - the helm trow a validation error, as expected.

So as there is a merge of values. To simplify


```yml
ingress:
   routes: hello-world
ingress.routes: ~
```

The library interprets it 
```json
{
  "ingress": { "routes": "~" }
}
```

Output is -> actual exception

or 

```json
{
  "ingress": { "routes": “hello-world },
   “ingress.route: ~
}
```

Output is -> unexpected exception Invalid rendering: %!s(<nil>)
