### ISSUE TITLE
Empty documents are considered failed templates

### ISSUE THREAD

**Issue by m-ildefons** [helm-unittest/helm-unittest#191]
## Problem

Consider the following situation. A chart that contains a template `validation.yaml` with only the following content:
```yaml
{{- if (empty .Values.someRequiredValue) }}
{{- fail "Please provide someRequiredValue" }}
{{- end }}
```
And a unit test that ensure this does not cause a failure when the value is given correctly:
```
---
suite: Validation
templates:
  - validation.yaml
tests:

  - it: Don't fail when value is provided
    set:
      someRequiredValue: "foobar"
    asserts:

      - notFailedTemplate: {}
```
This will not work because `validation.yaml` is an empty document and these are considered templating failures.

However the following check would pass:
```
---
suite: Validation
templates:
  - validation.yaml
tests:

  - it: Don't fail when value is provided
    set:
      someRequiredValue: "foobar"
    asserts:

      - hasDocuments
          count: 0
```

## Actual Result:

```
 FAIL  Validation       charts/tests/validation_test.yaml                                                                                                                                                                                                                                                                                                                                                                      
        - Don't fail when value is provided                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                - asserts[0] `notFailedTemplate` fail                                                                                                                                                                                                                                                                                                                                                                               
                         Template:       chartname/templates/validation.yaml 
```

## Expected Result:

The test should pass as templating did produce the expected result

Perhaps, if empty templates should by default be considered failures, an option to that test would be possible to override that? E.g.:
```
---
suite: Validation
templates:
  - validation.yaml
tests:

  - it: Don't fail when value is provided
    set:
      someRequiredValue: "foobar"
    asserts:

      - notFailedTemplate:
          allowEmptyDocument: true
```
