### ISSUE TITLE
0.3.4 - Test with just `hasDocuments` now failing

### ISSUE THREAD

**Issue by RyanW8** [helm-unittest/helm-unittest#194]
Hi,

We've just tried updating to version 0.3.4 of helm-unittest and have noticed that one of our test cases is now failing.

```
  - it: creates two documents
     hasDocuments:
       count: 2
```

This is a pretty simple test case which just checks that the template produces 2 YAML Documents. The error we receive is below:

```
 FAIL   workflow-chart/tests/configmap_test.yaml
        - Execution Error: 
                no asserts found


### Error:  no asserts found

```

**Comment by RyanW8** [comment]
Changing to 
```
  - it: creates two documents
    asserts:
      - hasDocuments:
          count: 2
```
Fixes this
