### ISSUE TITLE
Unknown path kubernetes.io/arch  in assert equals

### ISSUE THREAD

**Issue by straeger** [helm-unittest/helm-unittest#195]
Hello, 

I have the following test suite which should check the existence of a key and its value. 

```
  - it: deployment should have arm64 node selector
    asserts:
      - equal:
          path: spec.template.spec.nodeSelector.kubernetes.io/arch
          value: arm64
```

My question is regarding the very special key/ prop name in the end of the path 'kubernetes.io/arch'. I have tried to escape the key with '\' and by putting quotes arround it but with no luck.I allways get an unknown path error...

```
 - deployment should have arm64 node selector

                - asserts[0] `equal` fail
                        Template:       deployment.yml
                        DocumentIndex:  0
                        Error:
                                unknown path spec.template.spec.nodeSelector.kubernetes.io/arch
```

If I just check the value of nodeSelector with the following test, i can see that the property exists and the is the expected one.

```
  - it: deployment should have arm64 node selector
    asserts:
      - equal:
          path: spec.template.spec.nodeSelector
          value: arm64
```
Output: 
```
       - deployment should have arm64 node selector

                - asserts[0] `equal` fail
                        Template:       deployment.yml
                        DocumentIndex:  0
                        Path:   spec.template.spec.nodeSelector
                        Expected to equal:
                                arm64
                        Actual:
                                kubernetes.io/arch: arm64
                                kubernetes.io/os: linux
                        Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1,3 @@
                                -arm64
                                +kubernetes.io/arch: arm64
                                +kubernetes.io/os: linux
```

I have also tested the matchRegex assertion but the value of nodeSelector doesn't seem to be a string

```
  - it: deployment should have arm64 node selector
    asserts:
      - matchRegex:
          path: spec.template.spec.nodeSelector
          pattern: -arch$
```
result 

```

        - deployment should have arm64 node selector

                - asserts[0] `matchRegex` fail
                        Template:       deployment.yml
                        DocumentIndex:  0
                        Error:
                                expect 'spec.template.spec.nodeSelector' to be a string, got:
                                kubernetes.io/arch: arm64
                                kubernetes.io/os: linux
```

I am currently a little lost and could need an advice. What would be the correct way to test this property?

**Comment by straeger** [comment]
I found a solution:

```
  - it: deployment should have arm64 node selector
    asserts:
      - isSubset:
          path: spec.template.spec.nodeSelector
          content: 
            kubernetes.io/arch: arm64
```

But I still can't really figure why I am not able to access the property via the equals and path assertion.
