### ISSUE TITLE
Assertion for inline yamls

### ISSUE THREAD

**Issue by jcogilvie** [helm-unittest/helm-unittest#196]
I would like to parse a yaml file that is inside a field of my template.  

The aws secrets store csi driver expects a field similar to [this](https://github.com/aws/secrets-store-csi-driver-provider-aws#secretproviderclass-options):

```yaml
  parameters:
    objects: |
        - objectName: "MySecret"
          objectType: "secretsmanager"
```

But I am having trouble asserting on members of `objects`.  It would be great if there were some kind of function or assertion that could parse the value.

Right now the closest I've come is this failure on `equal`:

```yaml
      - equal:
          path: spec.parameters.objects
          value: "| 
          - objectName: \"secretName\""
```

```yaml
			Template:	api-service/templates/secrets-provider.yaml
			DocumentIndex:	0
			Path:	spec.parameters.objects
			Expected to equal:
				'| - objectName: "secretName"'
			Actual:
				|
				  - objectName: "secretName"
			Diff:
				--- Expected
				+++ Actual
				@@ -1,2 +1,3 @@
				-'| - objectName: "secretName"'
				+|
				+  - objectName: "secretName"
```

**Comment by denisbrainyyack** [comment]
In a similar case, I use `equal` assertion:
```yaml
templates:
  - templates/secretproviderclass.yaml
tests:
  - it: inline yamls
    asserts:
      - equal:
          path: spec.parameters.objects
          value: |-
            - objectName: "MySecret"
              objectType: "secretsmanager"
```

**Comment by quintush** [comment]
Hello @jcogilvie,

Before the assertions will be validated, all templates are already generated.
So the output will already contain static content (not template content).
In order to validate I would suggest to use the example of @denisbrainyyack.

For multiline, you indeed need to be carefull with the usage of | (keep newlines) or |- (keep newlines, but strip newline at the end), as the equal is validating very strict newlines.

Greetings,
@quintush

**Comment by jcogilvie** [comment]
This is a feature request, not a question.  I understand that the templates are already rendered.  

I don't want to use `equal` because in this case my content is a yaml list, and the order can vary and still be correct.  A regex match is more semantically correct as a "contains" in this case.  But I'd rather not have to, hence the feature request.

Knowing that yaml can contain blocks of yaml, and sometimes does in kubernetes--as in this example, or datadog, or argocd--I want a way to `toyaml` a string that is already present so that I can assert on the resulting object.

**Comment by Ceddaerrix** [comment]
Hello @quintush ,

I am currently in such a situation (for https://github.com/jenkinsci/helm-charts) for which I have the following content:
```
# Source: charts/jenkins/charts/jenkins/templates/jcasc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "me-jenkins-jcasc-config"
  namespace: "my-ns"
  labels:
    "app.kubernetes.io/name": jenkins
    "helm.sh/chart": "jenkins-4.6.5"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "me"
    "app.kubernetes.io/component": "jenkins-controller"
    amp-chart-jenkins-jenkins-config: "true"
data:
  jcasc-default-config.yaml: |-
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "${chart-admin-username}"
            name: "Jenkins Admin"
            password: "${chart-admin-password}"
      disableRememberMe: false
      mode: NORMAL
      numExecutors: 0
      labelString: ""
      projectNamingStrategy: "standard"
      markupFormatter:
        plainText
      clouds:
      - kubernetes:
          containerCapStr: "10"
          defaultsProviderTemplate: ""
          connectTimeout: "5"
          readTimeout: "15"
          jenkinsUrl: "http://me-jenkins.my-ns.svc.cluster.local:8080"
          jenkinsTunnel: "me-jenkins-agent.my-ns.svc.cluster.local:50000"
          maxRequestsPerHostStr: "32"
          name: "kubernetes"
          namespace: "my-ns"
          serverUrl: "https://kubernetes.default"
          podLabels:
          - key: "jenkins/me-jenkins-agent"
            value: "true"
          templates:
            - name: "default"
              namespace: "my-ns"
              id: 483af82f5b01edad4ca120763072d128278f9014c44ddf80cda69fb013a9b6a6
              containers:
              - name: "jnlp"
                alwaysPullImage: false
                args: "^${computer.jnlpmac} ^${computer.name}"
                command: 
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://me-jenkins.amp-helm.svc.cluster.local:8080/"
                image: "my-registry.com/virtual-docker/jenkins-pink-agent:3148.v532a_7e715ee3-7.0.5"
                privileged: "true"
                resourceLimitCpu: 512m
                resourceLimitMemory: 1Gi
                resourceRequestCpu: 512m
                resourceRequestMemory: 512Mi
                runAsUser: 
                runAsGroup: 
                ttyEnabled: false
                workingDir: /home/jenkins/agent
              idleMinutes: 0
              instanceCap: 2147483647
              imagePullSecrets:
              - name: regsecret
              label: "me-jenkins-agent "
              nodeUsageMode: "NORMAL"
              podRetention: Never
              showRawYaml: true
              serviceAccount: "default"
              slaveConnectTimeoutStr: "200"
              yamlMergeStrategy: override
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
    unclassified:
      location:
        adminAddress: 
        url: https://jenkins.example.com
```

and I want to validate that in `data.[jcasc-default-config.yaml]` I have:
```
    unclassified:
      location:
        adminAddress: 
        url: https://jenkins.example.com
```
or just that `unclassified.location.url` equals "https://jenkins.example.com"

Having the possibility to parse the content from `data.[jcasc-default-config.yaml]` into a YAML object (similarly to the `toYaml` function in helm) prior to asserting would ease any unit test on such content type.

Hence, what @jcogilvie has proposed with `parseYaml` would certainly add values to the _helm-unittest_ tool.

**Comment by sebdau** [comment]
I have exactly the same problem - testing complex config map data sections is too hard at the moment.

**Comment by isbalashov** [comment]
I have created an experimental assertion called stringContains, which might be what you were looking for. 

You can find more details [here](https://github.com/isbalashov/helm-unittest/blob/main/DOCUMENT.md).

I'm not exactly sure if it is semantically correct, though. 
This assertion allows you to check if a string contains a substring, ignore white spaces or tabs if needed, and also parse the string as JSON or YAML.

![Image](https://github.com/user-attachments/assets/687e9be5-3bec-4dd2-939f-53b9b2cf501f)

Here is how to use it:

```yaml
stringContains:
  path: data.text
  content: | 
    multiline
    string
  ignoreFormatting: true

stringContains:
  path: data.json
  fromJson: true
  content:
    key: value

stringContains:
  path: data.yaml
  fromYaml: true
  content:
    key: value
```
