### ISSUE TITLE
Exclude some keys during snapshot testing

### ISSUE THREAD

**Issue by denisbrainyyack** [helm-unittest/helm-unittest#197]
During the snapshot testing, we want to ignore some document keys that are important during the deployment of the chart, but are not important during development. For example, the key `help.sh/chart` , which is updated every time we update the version field in Chart.yaml.

It would be great if it were possible to specify such a configuration:
```yaml
templates:
  - templates/serviceaccount.yaml
tests:
  - it: Manifests should match snapshot
    asserts:
      - matchSnapshot:
          ignoreKeys:
            - "helm.sh/chart"
```
Expecting that in this case the snapshot would not contain keys with that name.
```yaml
Manifests should match snapshot:
  1: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: helm-unittest-snapshot-testing
        app.kubernetes.io/version: 1.16.0
        # Commented-out lines should not be generated when using the `ignoreKeys` settings.
        # helm.sh/chart: helm-unittest-snapshot-testing-0.1.0
      name: RELEASE-NAME-helm-unittest-snapshot-testing
```
