### ISSUE TITLE
Enable configuring release info in TestJob and default value cli

### ISSUE THREAD

**Issue by lrills** [helm-unittest/helm-unittest#2]
in TestJob:
```yaml
...
  - it: should...
    set:
        - a.b: c
    release:
      Name: my-release
      Namespace: my-space
      IsUpgrade: bool
      IsInstall: bool
      Revision: 9
```

in cli:
```
helm unittest --release-name=my-release --namespace=my-space .
```

Config in TestJob should have precedence over cli.

Options ref:
https://github.com/kubernetes/helm/blob/e8d80729ac20f402a80c5107b8b2513008de13fc/pkg/chartutil/values.go#L336-L343
