### ISSUE TITLE
Inadequate handling of error message when utilizing the `failedTemplate`

### ISSUE THREAD

**Issue by JuryA** [helm-unittest/helm-unittest#200]
## Error Description:

If the error message contains one or more colons (`:`), only the text following the final colon is considered as the error message.

### In my template, I employ the following code:

``` 
{{- fail "jdbc.injectTpl: Invalid TEMPLATE: Invalid" -}}
```

### My test approximately resembles the following segment:

```yaml
  - it: template [jdbc.injectTpl] should fail if TEMPLATE argument is invalid
    set:
      __test: '{{ include "jdbc.injectTpl" (dict "ROOT" $ "TEMPLATE" "Invalid") }}'
    asserts:
      - failedTemplate:
          errorMessage: "raw: jdbc.injectTpl: Invalid TEMPLATE: Invalid"
```

### Actual Output:

```
 FAIL  [jdbc.injectTpl] default tests for [jdbc.injectTpl]      tests/jdbc.injectTpl_test.yaml
        - template [jdbc.injectTpl] should fail if TEMPLATE argument is invalid

                - asserts[0] `failedTemplate` fail
                        Template:       test-chart/templates/NOTES.txt
                        DocumentIndex:  0
                        Expected to equal:
                                raw: jdbc.injectTpl: Invalid TEMPLATE: Invalid
                        Actual:
                                raw: Invalid
```

### Expected Output:

```
 PASS  [jdbc.injectTpl] default tests for [jdbc.injectTpl]      tests/jdbc.injectTpl_test.yaml
```
