### ISSUE TITLE
glob not resolving dash-case-filenames

### ISSUE THREAD

**Issue by rperryng** [helm-unittest/helm-unittest#201]
A snapshot spec defined like:

```
suite: Full Snapshot
templates:
  - '*.yaml'
tests:
  - it: matches the snapshot
    asserts:
      - matchSnapshot: {}
```

and a suite of files like:
```
❯ tree templates                       
templates
├── NOTES.txt
├── _helpers.tpl
├── dash-case-filename.yaml
├── deployment.yaml
├── hpa.yaml
├── ingress.yaml
├── service.yaml
└── serviceaccount.yaml
```

the `dash-case-filename.yaml` file won't be picked up by the snapshot.  Explicitly mentioning the file does seem to suffice as a work-around though.  That is to say:

```diff
suite: Full Snapshot
templates:
  - '*.yaml'
+ - dash-case-filename.yaml
tests:
  - it: matches the snapshot
    asserts:
      - matchSnapshot: {}
```

will include the `dash-case-filename.yaml` template in the snapshot.

Is this expected behaviour?  Helm docs seem to recommend using dashes in template filenames:

> Template file names should use dashed notation (`my-example-configmap.yaml`), not camelcase.
>
> ([source](https://helm.sh/docs/chart_best_practices/templates/#structure-of-templates))
