### ISSUE TITLE
Conditional assertions

### ISSUE THREAD

**Issue by jankoada** [helm-unittest/helm-unittest#203]
Hi, thanks for this great project. Is there a way to specify conditional assertions that if an annotation exists, it conforms to some regex?

I have this test:
```
suite: test service
templates:
  - service.yaml
tests:
  - it: DNS hostname is within length limit
    asserts:
      - matchRegex:
          path: metadata.annotations["external-dns.alpha.kubernetes.io/hostname"]
          pattern: "^(.{3,52}$"
```

But if annotation is not set, the test fails with `unknown path metadata.annotations["external-dns.alpha.kubernetes.io/hostname"]`. But I want the scenario of annotation not set to be valid as well. 

I did not find anything in the documentation on this topic, is it even supported?
