### ISSUE TITLE
containsDocument assertion fails in multi-document templates

### ISSUE THREAD

**Issue by peter-mcclonski** [helm-unittest/helm-unittest#205]
This is a new bug introduced in version 0.3.4.  Prior to this (tested: 0.3.2, 0.3.3), the following example passes without incident:

`templates/rbac.yaml`:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator
  namespace: default

```

`tests/rbac-test.yaml`:
```
suite: spark-operator
templates:
  - rbac.yaml
tests:
  - it: Should contain both ClusterRole and ClusterRoleBinding documents
    asserts:
      - containsDocument:
          kind: ClusterRole
          apiVersion: rbac.authorization.k8s.io/v1
      - hasDocuments:
          count: 2
```

Expected result: Success

Actual result: 
```
 FAIL  spark-operator   tests/rbac_test.yaml
        - Should contain both ClusterRole and ClusterRoleBinding documents

                - asserts[0] `containsDocument` fail
                        Template:       aissemble-spark-operator/templates/rbac.yaml
                        DocumentIndex:  1
                        Expected to contain document:
                                Kind = ClusterRole, apiVersion = rbac.authorization.k8s.io/v1, Name = , Namespace =
```

Removing the second document (the ClusterRoleBinding) from the template causes the test to pass, but this is not a desirable restriction, and represents a regression.
