### ISSUE TITLE
add option to override set value on test level

### ISSUE THREAD

**Issue by maratsal** [helm-unittest/helm-unittest#210]
Currently if values are set with `set` option on suit level they cannot be overridden on specific test level.

It would be great if test level set overrides values set on suit level set.

```
...
set:
  myOptions:
  - opt1
tests:
   - it: does some test
     set: # <- override here
         myOptions:
         - opt1
         - opt2
```

**Comment by quintush** [comment]
Hello @maratsal,

This behaviour should already be there.
Will check if i have validation in place to verify the behaviour.

Greetings,
@quintush

**Comment by stevelipinski** [comment]
A related issue I found is that it appears, if you set a dict value at a suite level, then override it in a test (say test #1), a subsequent test (test #2) then uses the value(s) set in test #1.  You almost have to re-override the value in test #2.

There's some strange merging going on when you set things at a suite level.

Here is what I have:
```
set:
  service.foo:
    port: 1234
tests:
  - it: test 1
    set:
      service.foo.type: NodePort
    asserts:
      - equal:
          path:  spec.type
          value: NodePort
  - it: test 2 - fails
    asserts:
      - equal:
          path: spec.type
          value: ClusterIP
```

That is a contrived situation to replicate what I'm seeing.  I'll dig a bit more and update this comment if I find out more, or if I have some other user-error on my side....
