### ISSUE TITLE
ConfigMap with embedded YAML file

### ISSUE THREAD

**Issue by hawksight** [helm-unittest/helm-unittest#213]
I've been trying to write some tests around the generation of a configmap with an embedded YAML file.

Eg my template looks something like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  labels:
    {{- include "jetstack-agent.labels" . | nindent 4 }}
data:
{{- if .Values.config.override.config }}
  config.yaml: |-
  {{- toYaml .Values.config.override.config | nindent 4 }}
{{- else }}
  config.yaml: |-
    server: {{ .Values.config.server | quote }}
    organization_id: {{ required "Organisation is a required input value" .Values.config.organisation }}
    cluster_id: {{ required "Cluster is a required input value" .Values.config.cluster }}
...
```

The problem I have in my test, is how to say, check that the generated `config.yaml` has the relevant contents.

I tried this:

```yaml
suite: test configuration overrides
templates:
  - templates/configmap.yaml

tests:
  # This checks the configmap is rendered properly when required config is given
  - it: render correctly when required config is given
    set: 
      config.organisation: test_org
      config.cluster: test_cluster
    template: configmap.yaml
    asserts:
      - equal:
          path: data
          value: config.yaml |-
            server: https://platform.jetstack.io
            organization_id: test_org
            cluster_id: test_cluster
            data-gatherers:
            # gather k8s apiserver version information
           ...
```

But get the following:

```log
 FAIL  	deploy/charts/jetstack-agent/tests/configuration_test.yaml
	- Execution Error: 
		yaml: line 58: mapping values are not allowed in this context
```

I could embed the whole thing as a string, but then I have to do the same to the expected value to make it match which is no longer testing a valid input.

I also tried removing the `|-` and I think that was better. But then it's no longer a valid configmap.

Does anyone do something similar? any good examples? I'm a little stuck how to test the configmap contents.

**Comment by hawksight** [comment]
For context I had a great suggestion from a colleague to use snapshots. (TY @davidcollom)

```yaml
  # This checks the configmap is rendered properly when required config is given
  - it: render correctly when only required config is given
    set: 
      config.organisation: test_org
      config.cluster: test_cluster
    template: configmap.yaml
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: ConfigMap
      - isAPIVersion:
          of: v1
      - matchSnapshot: {}
```

Where I just templated the end configmap and dumped the file over in `tests/__snapshot__/configuration_test.yaml.snap`

So I guess my question is if this the right approach in this type of scenario?
YAML config files seem fairly common.
