### ISSUE TITLE
Incorrectly handling the global value of subchart

### ISSUE THREAD

**Issue by zidoshare** [helm-unittest/helm-unittest#215]
I write this yaml file in sub chart:
```
namespace: {{ default .Release.Name .Values.global.namespace }}
```
if parent has default value is : `global.namespace: ""`

this test case is:
```
set: 
  global.namespace: "region1"
asserts:
  - equal:
     path: metadata.namespace
     value: region1
```

test result is:
<img width="957" alt="image" src="https://github.com/helm-unittest/helm-unittest/assets/11310504/18f4339f-155c-48db-8248-23398b53e2da">

but I use `helm template ` render this chart,result is:
```
❯ helm template --set global.namespace="region1" . -s charts/child-chart/templates/deployment.yaml
---
# Source: with-subchart/charts/child-chart/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: release-name-child-chart
  namespace: region1
```
