### ISSUE TITLE
Support assert 'failedTemplate' to catch a generic error message

### ISSUE THREAD

**Issue by vigyM** [helm-unittest/helm-unittest#218]
It would help if we can support assert 'failedTemplate' to catch a generic error message (catch all), without requiring to specify a specific message.

Something like:
```
tests:
  - it: 
    template:
    asserts:
      - failedTemplate:
          errorMessage: {}
```
Alternatively, this could be supported as well. Currently, doesn't seem to work in this manner
```
tests:
  - it: 
    template:
    asserts:
      - notFailedTemplate: {}
        not: true
```
