### ISSUE TITLE
Failure with v0.3.5 that it cannot find template file

### ISSUE THREAD

**Issue by camalot** [helm-unittest/helm-unittest#219]
Getting error with version `v0.3.5` that it is unable to locate the templates that are loaded by the test suite. this worked in `v0.3.4`

`template "<chart-name>/templates/deployment-foo.yaml" not exists or not selected in test suite`

``` yaml
---
suite: TEST SUITE
templates:
  - "deployment-foo.yaml"
values: []

tests:
  ...
```
