### ISSUE TITLE
Support assert 'failedTemplate' to catch a substring and regex in error message

### ISSUE THREAD

**Issue by ivankatliarchuk** [helm-unittest/helm-unittest#221]
It would help if we can support assert 'failedTemplate' to catch a regex or a substrict, without requiring to specify a full message.

Something like:

```
tests:
  - it: 
    template:
    asserts:
      - failedTemplate:
          contains: "a text"
      - failedTemplate:
          matchRegexPattern: "^namespace:"
```

The format could be any, as long as functionality is supported.
