### ISSUE TITLE
[Bug] Value leak between tests

### ISSUE THREAD

**Issue by ganto** [helm-unittest/helm-unittest#235]
I found that sometimes it might happen that values leak between different tests. I think there might be various reasons as this happened to me various times when writing tests. For now I found one easy way to reproduce it as following:

### Minimal Helm chart
* `values.yaml`
```yaml
config:
  foo:
    - bar
```
* Simple template rendering a ConfigMap: `templates/configmap.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  {{- toYaml .Values.config | nindent 2 }}
```

### Unittest
Now the following unit test:
```yaml
suite: test values
templates:
  - configmap.yaml
set:
  config:
    foo: null
tests:
  - it: should not render foo
    asserts:
      - notExists:
          path: data.foo
  - it: should render list with 2 elements
    set:
      config:
        foo:
          - bar
          - baz
    asserts:
      - lengthEqual:
          path: data.foo
          count: 2
  - it: should have a default list with 1 element
    asserts:
      - lengthEqual:
          path: data.foo
          count: 1
```
Resulting in the following error (unittest 0.3.5):
```
 FAIL  test values      tests/values_test.yaml                                                                                                                                                                                                                                                                                
        - should have a default list with 1 element

                - asserts[0] `lengthEqual` fail
                        Template:       test/templates/configmap.yaml
                        DocumentIndex:  0
                        Error:
                                count doesn't match as expected. expected: 1 actual: 2
                                expected result does not match
```

### Expectation

I would expect the last test to fail with an error that key `data.foo` doesn't exist. This was successfully tested with the first test as long as the `config.foo` value is not defined in the test. However, the values inserted in the second test (the `config.foo` list with two items) leak to the third test.

Interestingly if the `config.foo` list is not set to `null` via suite values the third test is successful and the `config.foo` values from the second test don't leak.

**Comment by bryanhorstmann** [comment]
I've just run into this myself.

Given the following test suite:
```
suite: tests deployments/deployment.yaml container images
templates:
  - templates/deployments/deployment.yaml
set:
  defaults:
    image:
      repository: nginx
      tag: stable
  deployments:
    app:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
```

And the following tests:
```
  - it: should use defaults.image if deployments.app.image is not set
    set:
      deployments:
        app:
          image:
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: nginx:stable
  - it: should use deployments.app.image instead of defaults.image
    set:
      deployments:
        app:
          image:
            repository: redis
            tag: latest
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: redis:latest
  - it: should use defaults.image.tag if only deployments.app.image.repository is set
    set:
      deployments:
        app:
          image:
            repository: redis
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: redis:stable
  - it: should use deployments.app.imagePath (deprecated) only if neither deployments.app.image and defaults.image are set
    set:
      defaults:
        image:
      deployments:
        app:
          imagePath: deprecatedImage
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: deprecatedImage
```

I get the following error:
```
 FAIL  tests deployments/deployment.yaml container images       tests/deployments_deployment_container_image_test.yaml
        - should use defaults.image.tag if only deployments.app.image.repository is set

                - asserts[0] `equal` fail
                        Template:       yoco-service-helm-chart/templates/deployments/deployment.yaml
                        DocumentIndex:  0
                        Path:   spec.template.spec.containers[0].image
                        Expected to equal:
                                redis:stable
                        Actual:
                                redis:latest
                        Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1,2 @@
                                -redis:stable
                                +redis:latest

        - should use deployments.app.imagePath (deprecated) only if neither deployments.app.image and defaults.image are set

                - asserts[0] `equal` fail
                        Template:       yoco-service-helm-chart/templates/deployments/deployment.yaml
                        DocumentIndex:  0
                        Path:   spec.template.spec.containers[0].image
                        Expected to equal:
                                deprecatedImage
                        Actual:
                                redis:latest
                        Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1,2 @@
                                -deprecatedImage
                                +redis:latest
```

It appears that once you use `set` in a test, it retains that for all future tests in a suite. I need to unset it in the next test. See the final test for an example.
```
  - it: should use defaults.image.tag if only deployments.app.image.repository is set
    set:
      deployments:
        app:
          image:
            repository: redis
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: redis:stable
  - it: should use deployments.app.image instead of defaults.image
    set:
      deployments:
        app:
          image:
            repository: redis
            tag: latest
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: redis:latest
  - it: should use deployments.app.imagePath (deprecated) only if neither deployments.app.image and defaults.image are set
    set:
      defaults:
        image:
      deployments:
        app:
          image: null
          imagePath: deprecatedImage
    asserts:
      - equal:
          path: spec.template.spec.containers[0].image
          value: deprecatedImage
```
