### ISSUE TITLE
`containsDocument` returning incorrect results when `not: true`

### ISSUE THREAD

**Issue by jarrettprosser** [helm-unittest/helm-unittest#239]
This is a similar issue as described in https://github.com/helm-unittest/helm-unittest/issues/173, but is present in 0.3.6 which should contain the fix from that issue. 

I am testing to confirm that a particular resource is _not_ being rendered when I set a value. The `containsDocument` assertion with `not: true` is returning a fail result when a resource with the `apiVersion` and `kind` I'm testing for are not present in the rendered output. I would expect that test to pass. 

To reproduce: 
- clone `helm-unittest`
- change directory to `test/data/v3/basic`
- run `helm unittest .` and all tests will pass
- add an assertion for `containsDocument`, specifying the created resource type:
```
      - containsDocument: 
          apiVersion: extensions/v1beta1
          kind: Deployment
```
- run tests, the new test will pass
- in `tests/deployment_test.yaml`, add an antonym assertion for a resource that is not created:
```
      - containsDocument: 
          apiVersion: exampleApiVersion/v1
          kind: Example
        not: true
```
- run tests again, and the new test will fail.
```
 FAIL  test deployment  tests/deployment_test.yaml
        - should pass all kinds of assertion

                - asserts[18] NOT `containsDocument` fail
                        Template:       basic/templates/deployment.yaml
```
- the test also fails if the new `any: true` is set
```
      - containsDocument: 
          apiVersion: exampleApiVersion/v1
          kind: Example
          any: true
        not: true
```

**Comment by emanuele-leopardi** [comment]
I'm new to this, my workaround is the following
```
suite: Ingress
templates:
  - ingress.yaml
tests:
  - it: No Ingress
    set:
      ingress.enabled: false 
    asserts:
      - hasDocuments:
          count: 0
 ```
so that when my chart has no ingress enabled the document count will be 0 ( i.e. no rendered document)
