### ISSUE TITLE
`apiVersion` is rendered as `null`  in specific cases

### ISSUE THREAD

**Issue by emanuele-leopardi** [helm-unittest/helm-unittest#242]
Hello, I've noticed that apiVersion is rendered as `null`, when there is the following situation:

hpa.yaml
```yaml
{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "autoscalingVersion" . }} <------
kind: HorizontalPodAutoscaler
...omissis
```
in `_helper.tpl` we have a function that sets the apiVersion according  to the  capabilities of the cluster  
```go
{{/*
Return available autoscaling version
*/}}
{{- define "autoscalingVersion" -}}
	{{- if .Capabilities.APIVersions.Has "autoscaling/v2" -}}
		autoscaling/v2
	{{- else if .Capabilities.APIVersions.Has "autoscaling/v2beta2" -}}
		autoscaling/v2beta2
	{{- else if .Capabilities.APIVersions.Has "autoscaling/v2beta1" -}}
		autoscaling/v2beta1
	{{- end -}}
{{- end -}}
```

Is there any workaround I can use to make this work , apart from setting something like 
```yaml
apiVersion: {{ include "autoscalingVersion" . | default "autoscaling/v2"}} 
```
