### ISSUE TITLE
Snapshot tests seem to 

### ISSUE THREAD

**Issue by pete-woods** [helm-unittest/helm-unittest#246]
(version: `0.3.6`)

When adding a new snapshot test, the tests always seem to pass if no snapshot has been created yet.

E.g. if I add a test case like this:
```
  - it: should do some stuff
    set:
      deployment:
        stuff: {}
    asserts:
      - matchSnapshot: {}
```
running `helm unittest ...` results in a pass.

It's only after I run with `-u`, and then change something that I can get a test failure.

**Comment by ryanvana** [comment]
An example of where this is a problem

```
{{- if .Values.feature.enabled --}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    deploymentName: {{ .Values.name }}
spec:
  env: {{ toYaml .Values.env | nindent 4 }}
{{- end -}}
```

Changing the `feature.enabled` property will cause the snapshot to update.
