### ISSUE TITLE
[feature request] assertions for multi line values

### ISSUE THREAD

**Issue by ensctom** [helm-unittest/helm-unittest#254]
I have a rendered helm chart like the following for a spring application

```

templateKeys:
    - key : config.yaml
      template: |
         server.port=8888
         spring.application.name=my-app

```

or

```
templateKeys:
    - key : config.yaml
      template: |
          spring:
            application:
              name: my-appp
```

currently I have to assert my template using
```
-it : test
  asserts:
    - matchRegex:
    - path: spec.templateKeys[0].template
    - pattern: spring.application.name=my-app
```
or
```
-it : test
  asserts:
    - matchRegex:
     - path: spec.templateKeys[0].template
       pattern: name=my-app
```
would by nice if I could assert using

```
-it : test
  asserts:
    - equal:
     - path: spec.templateKeys[0].template.spring.application.name
       value: my-app
``
