### ISSUE TITLE
Mock "now" time

### ISSUE THREAD

**Issue by rohit-gohri** [helm-unittest/helm-unittest#258]
I have a template that uses the ["now" function](https://helm.sh/docs/chart_template_guide/function_list/#now) to log some events on "post-upgrade". This causes the snapshot test to always fail. I would like to mock the value so that the snapshot returns the same value consistently

**Comment by ivankatliarchuk** [comment]
Hi, could you provide an example?

**Comment by rohit-gohri** [comment]
Hi! Sure. If you create a template like below and use snapshot tests, the snapshot will keep changing everytime you run the test

```yaml
timestamp: '{{ dateInZone "2006-01-02T15:04:05.000Z" (now) "UTC" }}'
```

Sample test:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json

suite: Test now
chart:
  version: 0.0.0
templates:
  - templates/test.yaml
tests:
  - it: should match snapshot
    asserts:
      - matchSnapshot: {}
```

**Comment by ivankatliarchuk** [comment]
Interesting. In Helm, which is primarily a package manager for Kubernetes, there isn't a direct mechanism for mocking or manipulating datetime values aka mocking. I wonder where something like this
```
# templates/test.yaml
timestamp: '{{ .Values.mock.timestamp | default (dateInZone "2006-01-02T15:04:05.000Z" (now) "UTC") }}'
```
and 
```yml
# tests/now_test.yaml

suite: Test now
chart:
  version: 0.0.0
templates:
  - templates/test.yaml
tests:
  - it: should match snapshot
    set:
       mock:
         timestamp: "'2024-01-07T100:33:52.385Z'"
    asserts:
      - matchSnapshot: {}
```

This isn't the optimal solution as it involves manipulating a Helm template.  Implementing a thorough mocking solution might require some time, and the maintainer's intentions for this process are currently uncertain.
