### ISSUE TITLE
Variable Reset / Encapsulation for tests

### ISSUE THREAD

**Issue by neo2k** [helm-unittest/helm-unittest#271]
Hello,

i think in some cases variables are not cleaned up completely between tests.

This part simply sets the testvalue:

```
        {{- if (.Values.env).testvalue }}
        - testvalue: {{ .Values.env.testvalue }}
        {{- end }}
```
The second unit test fails, but it should not. The variable "testvalue" is set in the second unit test, but it should not be set.

```
suite: testSuite
templates:
  - templates/deployment.yaml
set:
  env:
    key: value

tests:
  - it: test sets value
    set:
      env:
        testvalue: testvalue1
    asserts:
      - contains:
          path: spec.template.metadata.labels
          content: 
            testvalue: testvalue1

  - it: test does not set testvalue, should be empty in deployment
    asserts:
      - notContains:
          path: spec.template.metadata.labels
          content: 
            testvalue: testvalue1
```
Has anybody an idea? Maybe i have a mistake in my code. I think there ist maybe a problem with global variables set in testsuite.

I attach a full working example, just execute "run-helm-test.sh"

[20240104-unittest-framework-bug.zip](https://github.com/helm-unittest/helm-unittest/files/13858985/20240104-unittest-framework-bug.zip)
