### ISSUE TITLE
Allow multiple suites same test file

### ISSUE THREAD

**Issue by jdiegosierra** [helm-unittest/helm-unittest#272]
I'm testing helpers and want to have those tests in one file but group them by different suites. If I use `---` it just use the first suite. Would be nice to have this feature.

```yaml
suite: test helper 1
templates:
  - template1.yaml
tests:
  ...
---
suite: test helper 2
templates:
  - template2.yaml
tests:
 ...

```

Output:
```bash
helm unittest .

### Chart [ test ] .

 PASS  test helper 1	tests/template1.yaml

Charts:      1 passed, 1 total
Test Suites: 1 passed, 1 total
Tests:       11 passed, 11 total
Snapshot:    2 passed, 2 total
Time:        173.343708ms
```
