### ISSUE TITLE
`documentSelector` ignored during tests

### ISSUE THREAD

**Issue by fad3t** [helm-unittest/helm-unittest#275]
Hi everyone!

Thanks for maintaining this project, it is very useful 👍 

I'm trying to use the `documentSelector` filter to avoid hardcoding the document index, however my test is failing.
It looks like `unittest` is trying to validate the assertions against all the documents instead of the selected one.

Here's my test:
```yaml
---
suite: "test machine templates"
set:
  name: "unittest"
  virtualIp: "1.2.3.4"
tests:
- it: "should configure machine templates based on values"
  documentSelector:
    path: "metadata.name"
    value: "unittest-mt-great-template"
  set:
    machineTemplates:
      great-template:
        cpuSockets: 16
        memorySize: "64Gi"
        diskSize: "200Gi"
        imageName: "ubuntu-2204-kube-v1.28.5"
  asserts:
  - containsDocument:
      apiVersion: "infrastructure.cluster.x-k8s.io/v1beta1"
      kind: "NutanixMachineTemplate"
      name: "unittest-mt-great-template"
```

And the corresponding template:
```yaml
{{- range $name, $_ := .Values.machineTemplates }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixMachineTemplate
metadata:
  name: {{ $.Values.name }}-mt-{{ $name }}
spec:
  # omitted for brevity..
{{- end }}
```

The values file contains 4 predefined machines templates, so I have 5 in total considering the one added in the test.

Here's the test result:
```
	- should configure machine templates based on values

		- asserts[0] `containsDocument` fail
			Template:	cluster/templates/nutanix/nutanixmachinetemplate.yaml
			DocumentIndex:	0
			Expected to contain document:
				Kind = NutanixMachineTemplate, apiVersion = infrastructure.cluster.x-k8s.io/v1beta1, Name = unittest-mt-great-template, Namespace =
			DocumentIndex:	1
			Expected to contain document:
				Kind = NutanixMachineTemplate, apiVersion = infrastructure.cluster.x-k8s.io/v1beta1, Name = unittest-mt-great-template, Namespace =
			DocumentIndex:	2
			Expected to contain document:
				Kind = NutanixMachineTemplate, apiVersion = infrastructure.cluster.x-k8s.io/v1beta1, Name = unittest-mt-great-template, Namespace =
			DocumentIndex:	3
			Expected to contain document:
				Kind = NutanixMachineTemplate, apiVersion = infrastructure.cluster.x-k8s.io/v1beta1, Name = unittest-mt-great-template, Namespace =
```

If I explicitly set the `documentIndex` to 4 (so my 5th item, the one added in the test) it works without any problem.

Am I doing something wrong?

Thanks!
Fred
