### ISSUE TITLE
Global Variables are lost

### ISSUE THREAD

**Issue by neo2k** [helm-unittest/helm-unittest#276]
Hi,

fixing [Issue 271](https://github.com/helm-unittest/helm-unittest/issues/271)  created a new problem.

Global variable parent loses its children, when new children is added in local scope.

Example:

```
suite: testSuite
templates:
  - templates/deployment.yaml
set:
  parent:
    child1: child1

tests:
  - it: child1 is available
    asserts:
      - contains:
          path: spec.template.metadata.labels
          content: 
            testvalue: child1
  
  - it: child1 is lost when setting child2 -->> ERROR
    set:
      parent:
        child2: value
    asserts:
      - contains:
          path: spec.template.metadata.labels
          content: 
            testvalue: child1
```
Full example ist attached.

Any solution for this?

[20240111-unittest-framework-bug-2.zip](https://github.com/helm-unittest/helm-unittest/files/13902617/20240111-unittest-framework-bug-2.zip)

**Comment by kdhtrifork** [comment]
It is caused by https://github.com/helm-unittest/helm-unittest/blob/main/pkg/unittest/valueutils/valueutils.go#L98 which simply overwrites the key's value. 
I think this is intentional, as there is a supporting unit test for that case : https://github.com/helm-unittest/helm-unittest/blob/main/pkg/unittest/valueutils/valueutils_test.go#L98

I might be wrong?

**Comment by michaelruigrok** [comment]
> It is caused by https://github.com/helm-unittest/helm-unittest/blob/main/pkg/unittest/valueutils/valueutils.go#L98 which simply overwrites the key's value. I think this is intentional, as there is a supporting unit test for that case : https://github.com/helm-unittest/helm-unittest/blob/main/pkg/unittest/valueutils/valueutils_test.go#L98
> 
> I might be wrong?

I don't think that line is the cause, different `set` blocks merged just fine up until the last patch (i.e., 0.4.0 works with the above).

**Comment by michaelruigrok** [comment]
The workaround for this is to declare values you want merged on separate lines. The following will keep both variables set:

```yaml
set:
  parent.child1: child1
 tests:
    - it: child2 is available
      set:
        parent.child2: child2
```

If this change was intentional, it's probably worth noting in the change notes, and not making the change within a patch version. This change broke all of my tests, and for most others I expect the same to be the case.
