### ISSUE TITLE
Support regex assertion in snapshots

### ISSUE THREAD

**Issue by jdiegosierra** [helm-unittest/helm-unittest#280]
I want to check if any value is null:

```yaml
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      app: test-cluster
      app.kubernetes.io/version: null
```
```yaml
matchSnapshot:
  notMatchRegex:
    pattern: .*null.*
```
