### ISSUE TITLE
Print the rendered chart or section when failure

### ISSUE THREAD

**Issue by cornfeedhobo** [helm-unittest/helm-unittest#281]
I'm getting the strangest failures that only happen within unittest. When I feed the exact same values to helm, my renders are clean. I need a way to see what unittest is rendered, beyond the tiny little error message.

**Comment by quintush** [comment]
Hello @cornfeedhobo,

Currently working on it.
Still have some issues with proper handling of feature flags, which is blocking this enhancement.

Greetings,
@quintush

**Comment by tewfik-ghariani** [comment]
@cornfeedhobo would you like to share a reproducible scenario showcasing the failure you are facing? I would be interested in trying to help ^^

**Comment by cyfu** [comment]
@cornfeedhobo My workaround is to use the snapshot test. 
```yaml
tests:
  - it: should not change manifest
    templates:
      - deployment.yaml
    asserts:
      - matchSnapshot: {}
```
I put it as the first test case, and use `helm unittest . -u` to create a snapshot in the `__snapshot__` folder, now I can check how the deployment.yaml is rendered by helm unittest.

**Comment by jcogilvie** [comment]
How would we feel about adding a field `debug` to the schema of a test or suite to get this extra information?

**Comment by alexklibisz** [comment]
I think you can get the intended (or very close) behavior now by using the postRenderer feature.

Something like...

```yaml
postRenderer:
  cmd: tee
  args:
    - /tmp/my-test.yaml
```

Maybe there's a more elegant solution, but that's what I've been using. Just make sure you're on a recent version as this was introduced this year (2025). Wasted an hour or so wondering why this didn't work and turned out I was on a stale version.
