### ISSUE TITLE
`documentSelector` matches resources outside of `templates` map

### ISSUE THREAD

**Issue by michaelruigrok** [helm-unittest/helm-unittest#286]
In the example below, I would like to run some tests against the only Deployment defined in `templates/deploy.yaml`

tests/deploy_test.yaml:
```yaml
tests:
  - it: selects the correct kind
    templates:
      - templates/deploy.yaml
    documentSelector:
      path: kind
      value: Deployment
    asserts:
      - equal:
          path: kind
          value: Deployment
```
          
templates/deploy.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name
```

templates/another-deploy.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-name
```

Running this unit test throws the error `multiple indexes found`, because another deployment exists in `templates/another-deploy.yaml`

Instead, if `documentSelector` only evaluated documents produced by the files in test yaml's `templates` block (e.g. `templates/deploy.yaml`), it would make it much easier to match isolated test cases.
