### ISSUE TITLE
Test code block from _helpers.tpl

### ISSUE THREAD

**Issue by vovkanaz** [helm-unittest/helm-unittest#288]
Hello, is there any way to test such code block inside HELM template {{- include "setAffinity" . | nindent 8 }} using https://github.com/helm-unittest/helm-unittest, it seems like it doesn't support/work at least for now.

**Comment by JuryA** [comment]
I have shared my workaround for the missing functionality with you earlier. You can find the link to it in my previous message. We have been using this workaround for our tests for library charts. It involves exploiting the `NOTES.txt` file, which contains a helper template construct that allows us to test the named template by using a special value. We then compare the output of `NOTES.txt` with the `equalRaw` assertion to verify its accuracy. We are currently using this workaround until a better, native solution is available.

**Comment by ivankatliarchuk** [comment]
If I'm understand you correctly, [example](https://github.com/ik-workshop/helm-unittests-issues/tree/master/issue-288)

File `_affinities.tpl`

```yml
{{/*
Return a nodeAffinity definition
{{ include "common.affinities.nodes" . -}}
*/}}
{{- define "common.affinities.nodes" -}}
requiredDuringSchedulingIgnoredDuringExecution:
  nodeSelectorTerms:
  - matchExpressions:
    - key: topology.kubernetes.io/zone
      operator: In
      values:
      - antarctica-east1
      - antarctica-west1
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 1
    preference:
      matchExpressions:
      - key: another-node-label-key
        operator: In
        values:
        - another-node-label-value
{{- end -}}
```

File `pod.yaml`

```yml
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity: {{- include "common.affinities.nodes" . | nindent 8 }}
```

File `_test.yaml`

```yml
---
templates:
  - "pod.yaml"
tests:
  - it: should selects the correct kind and match snapshot
    documentSelector:
      path: kind
      value: Pod
    asserts:
      - matchSnapshot: {}
  - it: should validate path exists
    asserts:
      - exists:
          path: spec.affinity.nodeAffinity
```

And snapsho
```yml
should selects the correct kind and match snapshot:
  1: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: with-node-affinity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - antarctica-east1
                      - antarctica-west1
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: another-node-label-key
                      operator: In
                      values:
                        - another-node-label-value
                weight: 1
```

Everything just works fine. Are you expecting a feature where functions are `included` directly into test suites? This quite tricky, as there is nothing to generate for helm engine.
