### ISSUE TITLE
Path exists failed

### ISSUE THREAD

**Issue by cyfu** [helm-unittest/helm-unittest#291]
My helm template rendered like this:
```
      containers:
        - name: admin
          image: "xxx"
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsUser: 15000
            runAsGroup: 0
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - CHOWN
                - SETUID
                - SETGID
                - AUDIT_WRITE
            seccompProfile:
              type: Localhost
              localhostProfile: admin
```
I have written a test case to check if seccompProfile exists.
```
    asserts:
      - equal:
          path: spec.template.spec.securityContext.seccompProfile.type
          value: Localhost
      - equal:
          path: spec.template.spec.securityContext.seccompProfile.localhostProfile
          value: podseccompProfile
      - exists:
          path: spec.template.spec.containers[?(@.name=='admin')].securityContext.seccompProfile
      - exists:
          path: spec.template.spec.containers[?(@.name=='admin')].securityContext.capabilities.drop
```
The wired thing is the first exists test failed, but the second one succeeded. I also checked securityContext.privileged, or allowPrivilegeEscalation, and they worked as well. I can't figure out why the test failed to check securityContext.seccompProfile.

**Comment by tewfik-ghariani** [comment]
Are you talking about the second assertion?
```
      - equal:
          path: spec.template.spec.securityContext.seccompProfile.localhostProfile
          value: podseccompProfile
```
If so, that is the Pod security context and in case it is inheriting from the container security context in your template, then it is not working as expected because the value is wrong `podseccompProfile` != `admin`

Can you share the snippet related to the security context in your template?

**Comment by tewfik-ghariani** [comment]
I tested that locally and it worked for me without a problem, could you please share the snippet related to the securityContext in your template?

**Comment by cyfu** [comment]
The template looks like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-xxx-admin
  labels:
    app.kubernetes.io/name: xxx-admin
    helm.sh/chart: xxx-admin-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: xxx-admin
      app.kubernetes.io/instance: release-name
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xxx-admin
        app.kubernetes.io/instance: release-name
      annotations:        
        container.apparmor.security.beta.kubernetes.io/admin: "localhost/admin"
    spec:
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: imgcred
      serviceAccountName: "xxx-admin-service-account"
      automountServiceAccountToken: false
      securityContext:        
        seccompProfile:
          type: Localhost
          localhostProfile: podseccompProfile
      containers:
        - name: admin
          image: "xxx:latest"
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsUser: 15000
            runAsGroup: 0
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - CHOWN
                - SETUID
                - SETGID
                - AUDIT_WRITE
            seccompProfile:
              type: Localhost
              localhostProfile: admin
          envFrom:
          - configMapRef:
              name: release-name-xxx-admin-configmap
```
I also checked helm unittest version, and upgraded it from 0.4.0 to 0.4.1.
```bash
❯  helm plugin list unitest
NAME            VERSION         DESCRIPTION                                                                         
diff            3.5.0           Preview helm upgrade changes as a diff                                              
helm-git        0.11.2          Get non-packaged Charts directly from Git.                                          
secrets         4.0.0-dev       This plugin provides secrets values encryption for Helm charts secure storing       
unittest        0.4.0           Unit test for helm chart in YAML with ease to keep your chart functional and robust.

❯ helm plugin update unittest

❯ helm plugin list unitest
NAME            VERSION         DESCRIPTION                                                                         
diff            3.5.0           Preview helm upgrade changes as a diff                                              
helm-git        0.11.2          Get non-packaged Charts directly from Git.                                          
secrets         4.0.0-dev       This plugin provides secrets values encryption for Helm charts secure storing       
unittest        0.4.1           Unit test for helm chart in YAML with ease to keep your chart functional and robust.
❯ helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}
```
However the issue is still there.
```
- asserts[2] `exists` fail
		Template:       mychart/charts/sub-chart1/templates/deployment.yaml
		DocumentIndex:  0
		Path:   spec.template.spec.containers[?(@.name=='admin')].securityContext.seccompProfile expected to exists
```
