### ISSUE TITLE
Mocking getHostByName

### ISSUE THREAD

**Issue by OOTS** [helm-unittest/helm-unittest#299]
Hello,

I'd like to request a feature: Mocking `getHostByName` (and maybe similar helm functions) for the unit-tests.

I'm a big fan of `getHostByName`, I frequently use it to in my networkpolicies to resolve hostnames (e.g. of a database server) and allow-list traffic to that. E.g.:

```
egress:
  - to:
    - ipBlock:
        cidr: {{ getHostByName .Values.database.hostname }}/32
    ports:
    - port: {{ quote .Values.database.port }}
      protocol: TCP
```

(Using this function requires running helm with `--enable-dns`.)

However, when unit-testing this, I face some issues:

Firstly, `helm unittest .` does not seem to work with the `--enable-dns` flag. Both `helm --enable-dns unittest .` and `helm unittest --enable-dns .` produced errors when I tried it. Running `helm unittest .` just produces `cidr: /32`.

Secondly, without mocks, it's not really clear what hostname I should put into my test values. It would have to be a hostname that resolves to a single, unique IP, so none of the big global sites (google.com, facebook.com, wikipedia.com, ...) will work. (Now that I think of it, `localhost` *might* work.)

Therefore, I would like to have the ability to inject mock data that will be returned by `getHostByName`, if that's possible.

For now, I've defined a template called `mockableGetHostByName` in my `_helpers.tpl` that looks into `.Values.mock.getHostByName` first and returns data from there (if available) and calls the real `getHostByName` function otherwise. However, this seems more of a hack than a real solution to me.

I'd be interested in hearing your thoughts about this :)
