### ISSUE TITLE
Template path is translated differently 

### ISSUE THREAD

**Issue by cyfu** [helm-unittest/helm-unittest#300]
In the `test/data/v3/with-subchart` folder, run `helm unittest .` command, all the test suites pass as expected.
but if I just want to run one of the test suite, by specifying test suite file name, 
`helm unittest . -f charts/child-chart/tests/deployment_test.yaml`, it fails to translate the templates path.
```
 FAIL  test deployment  charts/child-chart/tests/deployment_test.yaml
        - should pass all kinds of assertion

                - asserts[3] `matchRegex` fail
                        Template:       with-subchart/templates/deployment.yaml
                        DocumentIndex:  0
                        Path:   metadata.name
                        Expected to match:
                                ^.*-child-chart$
                        Actual:
                                RELEASE-NAME-with-subchart
```
In the `charts/child-chart/tests/deployment_test.yaml` file, 
```
templates:
  - templates/deployment.yaml
```

`templates/deployment.yaml` now is translated to `with-subchart/templates/deployment.yaml`, it should be `with-subchart/charts/child-chart//templates/deployment.yaml`. And the test values file also needs to be adjusted to move under the subchart.

The expectation is test suites always be executed under the same context, no matter how the cli command is executed.
