### ISSUE TITLE
documentSelector not working with 0.4.3 update

### ISSUE THREAD

**Issue by old-guy-coder** [helm-unittest/helm-unittest#312]
I have just updated to use Helm unittest `0.4.3` and all my test began to fail with `Error: document not found`

```
  - it: should create find document
    documentSelector:
      path: kind
      value: DatabaseAccount
    asserts:
      - matchSnapshot: {}
```

The above test is an example of a test that is not working, and returns the above error, if you remove the `documentSelector` then the test does succeed and create the snapshot and I can see the resources listed in the snapshot

I have rolled back to `0.4.2` and the tests do complete successfully in that version

helm-unittest: `0.4.3`

**Comment by ivankatliarchuk** [comment]
Hi. Could you please share a snippet to reprdouce?

**Comment by ivankatliarchuk** [comment]
There is a test `https://github.com/helm-unittest/helm-unittest/tree/main/test/data/v3/with-document-select` possibly your case is not covered.

**Comment by ivankatliarchuk** [comment]
A bug was fixed, which could potentially impact your snapshot. You may need to regenerate it to ensure everything is updated. Still worth to share `old` and `new` snapshots.

**Comment by jpuskar** [comment]
In my case, I had the 'templates' key at the root, instead of inside each test block (starting with `- it:`).
Moving 'templates' into each test block fixed it.

**Comment by kaisen-san** [comment]
Same issue here.

**Comment by ivankatliarchuk** [comment]
Any examples to reproduce?

**Comment by kaisen-san** [comment]
Anything with templates at the root. Taking your test as an example, this should fail:

```yaml
suite: Document Selector test
templates:
  - templates/deployment.yaml
tests:
  - it: selects the correct kind when templates provided
    documentSelector:
      path: kind
      value: Deployment
    asserts:
      - equal:
          path: kind
          value: Deployment
      - hasDocuments:
          count: 1
```

**Comment by leogps** [comment]
Is there going to be a release with a fix for this in the near future? Builds are failing for us, contemplating whether to move the "documentSelector" everywhere or wait for the fix.
Thanks.

**Comment by ivankatliarchuk** [comment]
Roll back the version, is possibly the best option at the moment. If your test is differ to one proposed in the pull request, share your failing scenario.

**Comment by jpuskar** [comment]
If you decide to make a change, please consider a forward-fix that allows both methods as we have already moved templates for documentSelector. Either way thank you for making this awesome software.

**Comment by old-guy-coder** [comment]
> Hi. Could you please share a helm chart or relevant parts of it to reproduce the bug?
> 
> A bug was fixed, which could potentially impact your snapshot. You may need to regenerate it to ensure everything is updated. Still worth to share `old` and `new` snapshots.

Here is a test that reproduces the issue with `0.4.3`

```
suite: Document Selector test
templates:
  - infra.yaml
tests:
  - it: should create find document
    documentSelector:
      path: kind
      value: DatabaseAccount
    asserts:
      - matchSnapshot: {}
```
