### ISSUE TITLE
`containsDocument` with `not` flag still not working (v0.4.4)

### ISSUE THREAD

**Issue by jcogilvie** [helm-unittest/helm-unittest#316]
Same issue as #145 on the same test after upgrading to v0.4.4.

The test, the underlying chart, and the template result listed in that issue are all identical.  I have also tried and failed to use `any: true` to no effect.  

Test:

```yaml
  - it: has no ScaledObject when autoscaling is disabled (default)
    set:
      commitSha: 12345
      autoscaling:
        enabled: false
    asserts:
      - containsDocument:
          kind: ScaledObject
          apiVersion: keda.sh/v1alpha1
        # invert the assertion
        not: true
```

Chart template:

```
{{- if .Values.autoscaling.enabled }}
{{ include "lib.autoscaling" .}}
{{- end -}}
```

(which obviously should not render any objects when autoscaling.enabled is false)

`helm template` output does not contain any `autoscaling.yaml`, as evidenced by this (correct) failure:

When running without `not: true` this is the failure (which is expected):

```
 FAIL  test autoscaling configuration	tests/autoscaling_test.yaml
	- has no ScaledObject when autoscaling is disabled (default)

		- asserts[0] `containsDocument` fail
			Template:	terminus-api-service/templates/autoscaling.yaml
			DocumentIndex:	0
			Expected to contain document:
				Kind = ScaledObject, apiVersion = keda.sh/v1alpha1, Name = , Namespace =
```

When running with `not: true` this is the failure (which is unexpected):

```
 FAIL  test autoscaling configuration	tests/autoscaling_test.yaml
	- has no ScaledObject when autoscaling is disabled (default)

		- asserts[0] NOT `containsDocument` fail
			Template:	terminus-api-service/templates/autoscaling.yaml
```
