### ISSUE TITLE
How to use `contains` for a list within a list

### ISSUE THREAD

**Issue by Kellen275** [helm-unittest/helm-unittest#319]
In my particular case, I'm attempting to check if a Deployment contains a container that mounts a particular volume. However, I have multiple volumeMounts that I'm not concerned with

I.e., I want to verify the following exists
```yaml
# deployment.yaml
spec:
  template:
    spec:
      containers:
        - name: RELEASE-NAME
          volumeMounts:
            - mountPath: /my-volume
              name: my-volume
```

I'm attempting to use the following `example_test.yaml`
```yaml
suite: example test
templates:
  - deployment.yaml
tests:
  - it: Should Mount Volume
    asserts:
      - contains:
          any: true
          path: spec.template.spec.containers
          content:
            name: RELEASE-NAME
            volumeMounts:
              - mountPath: /my-volume
                name: my-volume
```

However, it appears that the `any: true` doesn't propagate
```sh
$ helm unittest .

### Chart [ example ] .

 FAIL  example test tests/example_test.yaml
    - Should Mount Volume

        - asserts[0] `contains` fail
            Template:   example/templates/deployment.yaml
            DocumentIndex:  0
            Path:   spec.template.spec.containers
            Expected to contain:
                - name: RELEASE-NAME
                  volumeMounts:
                    - mountPath: /my-volume
                      name: my-volume
            Actual:
                - name: RELEASE-NAME
                  volumeMounts:
                    - mountPath: /my-volume
                      name: my-volume
                    - mountPath: /tmp
                      name: tmp
```

**Comment by Kellen275** [comment]
My temporary workaround is assuming the first container, as opposed to an arbitrary container with `name: RELEASE-NAME`.

The following test succeeds
```yaml
asserts:
  - contains:
      any: true
      path: spec.template.spec.containers[0].volumeMounts
      content:
        mountPath: /my-volume
        name: my-volume
```

**Comment by quintush** [comment]
Hello @Kellen275,

The contains assertion can only validate 1 level deep.
So in your example it can only validate the object structure of the container object and not the container/volumeMount object.

As the focus of youre is pointing to the volumeMounts, the best way to use contain is by setting a more strict path that identifies the volumeMounts

```yaml
suite: example test
templates:
  - deployment.yaml
tests:
  - it: Should Mount Volume
    asserts:
      - contains:
          any: true
          path: spec.template.spec.containers[0].volumeMounts
          content:
            mountPath: /my-volume
            name: my-volume
```
or (when using jsonPath selector in the path)
```yaml
suite: example test
templates:
  - deployment.yaml
tests:
  - it: Should Mount Volume
    asserts:
      - contains:
          any: true
          path: spec.template.spec.containers[?(@.name == "RELEASE-NAME")].volumeMounts
          content:
            mountPath: /my-volume
            name: my-volume
```

Greetings,
@quintush
