### ISSUE TITLE
question on test for "all" template files

### ISSUE THREAD

**Issue by epDHowwD** [helm-unittest/helm-unittest#320]
To test that every object has an app label or something like a support link, I would like to formulate a test like this:

``` yaml 
suite: test app label
templates:
  - templates/*.yaml
tests:
- it: object has app label
  asserts:
  - equal:
      path: metadata.labels.app
      value: myapp
```

According to [documentSelector](https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md#test-job) this should default select "all" documents within every (*.yaml) template file.

Now the document structure already has some template surrounded by feature flags, so some files might render empty, and thus do not comprise documents. 

`templates/file-v1.yaml`:
```
{{- if .Values.features.magic }}
  # see file-v2.yaml
{{- else }}
{{- end }}
```

`templates/file-v2.yaml`:

```
{{- if .Values.features.magic }}
{{- end }}
```

I would expect that asserts on _all_ documents in _all_ templates would somehow accept empty templates, but the assert fails if not at least one document can be found per template. As I see certainly why asserts should raise if no document is fulfilling the assert, I would like to know if it is possible to test this similarly?
