### ISSUE TITLE
How to remove newlines from expected value in equal assertion?

### ISSUE THREAD

**Issue by mathe-matician** [helm-unittest/helm-unittest#322]
I have a subchart test that has this basic test:

```yaml
suite: Service test suite
templates:
  - templates/deployment.tpl
tests:
  - it: Test service deployment
    set:
      global.image.repository: test-repo.com/
      global.image.tag: v99.99.99
    asserts:
      - notFailedTemplate: {}
      - equal:
          path: spec.template.spec.imagePullSecrets[0].name
          value: regcred
      - equal:
          path: .spec.template.spec.containers[0].image
          value: test-repo.com/service:v99.99.99
```

This tests the deployment's image repo and tag templating:

```yaml
image: {{ required "Image repo required." .Values.global.image.repository }}service:{{ required "Image tag required" .Values.global.image.tag }}
```

I call this subchart's test from the umbrella parent chart like this:

```
helm unittest . --debug -d
```

The subchart's test always fails because a newline is included in the `equal`'s expected content.

```
time="2024-04-15T17:00:05-05:00" level=debug msg="expected content: test-repo.com/service:v99.99.99\n" validator=equal
time="2024-04-15T17:00:05-05:00" level=debug msg="actual content: test-repo.com/service:v99.99.99" validator=equal
```

How do I avoid this newline in the expected assertion?
