### ISSUE TITLE
Execute Error when using syntax about Automatically Roll Deployments

### ISSUE THREAD

**Issue by lianneli** [helm-unittest/helm-unittest#324]
The related content of Template is:
```
spec: 
  replicas: 1
  selector:
    matchLabels:
      {{- include "aaa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/conf: {{ include (print $.Template.BasePath "/aaa-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "aaa..selectorLabels" . | nindent 8 }}
```

The line `{{ include (print $.Template.BasePath "/aaa-configmap.yaml") . | sha256sum }}`  is supported in Helm website(https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-include-function) 
![image](https://github.com/helm-unittest/helm-unittest/assets/19421187/ba58c1a0-ecc1-44bb-a8c6-235be5a17bf6)

But get failed when using `helm unittest`:

```
Error: template: aaa/templates/aaa-deployment.yaml:32:26: executing "aaa/templates/aaa-deployment.yaml" at <include (print $.Template.BasePath "/aaa-configmap.yaml") .>: error calling include: template: no template "aaa/templates/aaa-configmap.yaml" associated with template "gotpl"
```

It runs well in --dry-run:
```
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aaa
      app.kubernetes.io/instance: aaa-1714114692
  template:
    metadata:
      annotations:
        checksum/conf: d2d2d417f84088dbdda0356c3473cabe93ac21ed024c9efd318285ec2588a8ea
      labels:
        app.kubernetes.io/name: aaa
        app.kubernetes.io/instance: aaa-1714114692
```
