### ISSUE TITLE
Feature: isType assertition

### ISSUE THREAD

**Issue by rquinio1A** [helm-unittest/helm-unittest#325]
I didn't find a way to assert the type of a specific value (string, number, boolean, ...)
My use case would be to check that all K8s container env values have type string, otherwise it causes error like "cannot convert int64 to string".

Something like:

```yaml
- isType:
    path: spec.template.spec.containers[0].env[value]
    type: string
```
