### ISSUE TITLE
`no asserts found` (v0.5.0)

### ISSUE THREAD

**Issue by viceice** [helm-unittest/helm-unittest#329]
The new version v0.5.0 is erroring on one of our files:

```yaml
suite: Init template
release:
  name: forgejo-unittests
  namespace: testing
templates:
  - templates/gitea/init.yaml
tests:
  - it: runs gpg in batch mode
    set:
      signing.enabled: true
      signing.privateKey: |-
        -----BEGIN PGP PRIVATE KEY BLOCK-----
        {placeholder}
        -----END PGP PRIVATE KEY BLOCK-----
    asserts:
      - equal:
          path: stringData["configure_gpg_environment.sh"]
          value: |-
            #!/usr/bin/env bash
            set -eu

            gpg --batch --import /raw/private.asc

```

I have no clue what the error is and the debug parameter does nothing.

```
 helm unittest --debugPlugin --strict -f 'unittests/init/init_directory_structure.sh-rootless.yaml'  ./ 
 FAIL   unittests/init/init_directory_structure.sh-rootless.yaml
        - Execution Error:
                no asserts found


### Error:  no asserts found


Charts:      1 failed, 1 errored, 0 passed, 1 total
Test Suites: 1 failed, 1 errored, 0 passed, 1 total
Tests:       0 passed, 0 total
Snapshot:    0 passed, 0 total
Time:        14.6247ms

Error: plugin "unittest" exited with error
```

- https://codeberg.org/forgejo-contrib/forgejo-helm/pulls/446

**Comment by mpeuster** [comment]
We are facing the same issue with our tests, after we updated to 0.5.0.

Example test that fails:

```
tests:
  - it: example
    values:
      - ../values.yaml
    set:
      secret:
        password: somepassword
        username: admin
    documentIndex: 0
    asserts:
      - containsDocument:
          kind: Secret
          apiVersion: v1
      - equal:
          path: metadata.name
          value: env-secret
```

It works when downgrading to 0.4.4, though. I have no more details yet.
