### ISSUE TITLE
yaml: unmarshal errors when having multiple deployments configs in the same file

### ISSUE THREAD

**Issue by assapir** [helm-unittest/helm-unittest#330]
we have a template with the following:
```yaml
{{- if ... }} # this is always true by default
apiVersion: apps/v1
kind: Deployment
...
---
apiVersion: apps/v1
kind: Deployment
...
```

When trying to write a simple test, we get the following error:
```
                Error: yaml: unmarshal errors:
  line 63: mapping key "kind" already defined at line 2
  line 64: mapping key "metadata" already defined at line 3
  line 71: mapping key "spec" already defined at line 10
```

If I comment out the first deployment, everything is working as expected.

**Comment by asweet-confluent** [comment]
This happened when I accidentally chomped the whitespace before my document separator:
```yaml
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsOnly--- # <--
apiVersion: apps/v1
kind: Deployment
```

Fixing that resolved the problem.

**Comment by mikefox** [comment]
I have this issue with two ServiceAccount objects and it only occurred when the second object was wrapped in an IF statement:

Works:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: support
```

Doesn't work:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
{{- if .Values.supportPod.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: support
{{- end }}
```

My test config includes:

```
    set:
      supportPod.create: true
```
