### ISSUE TITLE
`contains` fails to detect string element in array

### ISSUE THREAD

**Issue by peter-mcclonski** [helm-unittest/helm-unittest#342]
Given the following toy test:
```
  - it: When specifying jar dependencies, each dependency is appropriately listed for download
    set:
      dependencies.jars:
        - some_jar.jar
        - another_jar.jar
    asserts:
      - contains:
          path: spec.template.spec.initContainers[1].command
          any: true
          content: some_jar.jar
```

The following output is produced:

```
                - asserts[0] `contains` fail
                        Template:       mychart/templates/deployment.yaml
                        DocumentIndex:  0
                        Path:   spec.template.spec.initContainers[1].command
                        Expected to contain:
                                - some_jar.jar
                        Actual:
                                - wget
                                - -P
                                - /tmp/jars/
                                - some_jar.jar
                                - another_jar.jar

```

The output itself seems to suggest that the expected text is present.  However, the assertion fails.

Helm unittest plugin version:  0.5.1

**Comment by ivankatliarchuk** [comment]
Any chance to provide more details on your scenario? Full template and full suite file with relevant values files probably needed. Or share linkt if it's public helm chart

**Comment by Fabccc** [comment]
Removing the `any: true` when checking a single value worked in my case.
But when checking if an array of string contains another array of string it does not work

**Comment by ivankatliarchuk** [comment]
I need examples and a minimal test suite, including the YAML template, to be able to reproduce these cases. Please share them.

**Comment by ewilkins-csi** [comment]
Template:
```yaml
command: ['one', 'two', 'three']
```

Test Suite:
```yaml
Suite: Example

templates:
  - example.yaml

tests:
  - it: Contains fails with any
    asserts:
      - contains:
          path: command
          any: true
          content: two
```

The test passes if `any` is excluded/`false`, but fails otherwise. This is the same behavior as documented in #394  I think this might just be a misunderstanding of what the `any` parameter actually means.  At first blush, it sounds like it means that `any` will allow the assertion to succeed if _any_ entry in the array matches the given `content`, and `any: false` will require that _all_ of the array matches the `content`. Given that the assertion is _contains_, I don't think that interpretation of `any` makes sense on its face as it would effectively make `contains` and `equals` synonymous.  It seems much more likely to me (and by my cursory glance at the code) that `any` is more of a "partial match" flag. So that a single entry in the array can match `content` if _any sub-property_ of that entry matches `content`.

I'm no wordsmith and naming is hard, but perhaps the README could be updated to clarify this. E.g.:
> any: bool, optional. for arrays of object, allows `content` to be a subset of the full object


With all of that said, it does seem like a bug that specifying `any` would fail for an exact string match of an entry with the content. I am not very familiar with Go, but I think [calling range](https://github.com/helm-unittest/helm-unittest/blob/main/pkg/unittest/validators/contains_validator.go#L43) on the single entry when the entry is a string is causing odd behavior for `validateSubset` (though to be honest I'm not sure how the `!v.Any` branch is working if this is the case.)
