### ISSUE TITLE
When using `lengthEqual.path` it should be possible to use `count=0`

### ISSUE THREAD

**Issue by AndersBennedsgaard** [helm-unittest/helm-unittest#346]
I want to test if the number of volumes in a Pod is zero, when you haven't specified that you want any.
So I wanted to make use of the following:

```yaml
tests:
  - it: should have no volumes
    asserts:
      - lengthEqual:
          path: spec.template.spec.volumes
          count: 0
```

However, this fails with `Error: 'count' field must be set if 'path' is used`
The reason for this is the following piece of code:

https://github.com/helm-unittest/helm-unittest/blob/96d1ad41ca628db9d10d2ac883d5d5e663efda48/pkg/unittest/validators/length_equal_document_validator.go#L68

For validating that a user have passed in an integer for `count`, we can't check if `count == 0`. However, if we used a pointer to an integer instead, then we could check if `count == nil` which it would only be if the user haven't passed in a `count`
