### ISSUE TITLE
Feature: isValidScheme - Test a document against a scheme

### ISSUE THREAD

**Issue by ShimiTaNaka** [helm-unittest/helm-unittest#351]
Most of the assertions are great to test how different
templates in the chart behave per different inputs.
Using a whole document is great as well, but neither one of them
actually assures that when applied to kubernetes, the scheme will be valid.
would be great if it would be possible to specify:
```yaml
- isValidScheme:
    schemes:
     - https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/crds/karpenter.sh_nodeclaims.yaml
```
for example assert scheme compliance
