### ISSUE TITLE
`failedTemplate` fails with `values.schema.json`

### ISSUE THREAD

**Issue by ata-ata** [helm-unittest/helm-unittest#363]
`failedTemplate` fails if provided values are not validated correctly against the chart's `values.schema.json`.

To reproduce, start with an empty helm chart with this `values.schema.json`:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "value": {
        "type": "string"
      }
  }
}
```
And this test should fail:
```
suite: test suite
tests:
  - it: should succeed
    set:
      value: null
    asserts:
      - failedTemplate: {}
```

My understanding is that this test should succeed.
