### ISSUE TITLE
`lengthEqual` should not accept negative values

### ISSUE THREAD

**Issue by ivankatliarchuk** [helm-unittest/helm-unittest#368]
https://github.com/helm-unittest/helm-unittest/pull/358#discussion_r1710974927

Currently `count` parameter accepts negative values. It should be a fail fast input validation, so that count always positive integer or ZERO

```
tests:
  - it: should fail fast as count is negative
    asserts:
      - lengthEqual:
          path: spec.template.spec.volumes
          count: -29
  - it: should not fail fast
    asserts:
      - lengthEqual:
          path: spec.template.spec.volumes
          count: 1
```
