### ISSUE TITLE
allow lookup of resources defined in `kubernetesProvider` without any objects

### ISSUE THREAD

**Issue by michaelruigrok** [helm-unittest/helm-unittest#380]
In Helm, you can call lookup in the form `lookup "v1" "ServiceAccount" "" ""`. This provides a list of all objects of the given kind (i.e. ServiceAccount). If no such objects exist, the function returns an empty list. In my use case, this call is a useful heuristic for checking if Helm is dynamically setting fields based on the server context or not, letting me flag to users which values may dynamically change after apply (see appendix for more info).

However, in helm-unittest running a template containing this function call without any objects defined throws an error before it can properly execute tests. This leads to situations where the template is valid but tests fail to run.

`template: templates/lookup.yaml:4:15: executing "templates/lookup.yaml" at <lookup "v1" "ServiceAccount" "" "">: error calling lookup: coding error: you must register resource to list kind for every resource you're going to LIST when creating the client.  See NewSimpleDynamicClientWithCustomListKinds or register the list into the scheme: /v1, Resource=serviceaccounts out of map[]`

A simple replication of this issue is as follows:

templates/lookup.yaml:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{- if lookup "v1" "ServiceAccount" "" "" -}}a{{- else -}}b{{- end -}}
```

tests/lookup_test.yaml:
```yaml
kubernetesProvider:
  scheme:
    v1/ServiceAccount:
      gvr:
        version: v1
        resource: serviceaccounts
      namespaced: true
  objects: []

tests:
  - asserts:
      - equal:
          path: kind
          value: Secret
```

If the objects list is changed to add a service account, the exception subsides:

```yaml
  objects:
    - kind: ServiceAccount
      apiVersion: v1
```

Looking up a specific object by its name (eg. `lookup "v1" "ServiceAccount" "" "default"`) will also work, and serves as a decent workaround until this issue is fixed. However, this workaround prevents a wide array of uses for the `lookup` function.

### Appendix
Since a service account is created by default, and any workload requires a service account, one almost always exists. Thus, if `lookup` returns an empty list, this is a very strong indicator that Helm is not connected to a server context. In such a circumstance, Helm does not execute `lookup`, instead it simply returns an empty list.

**Comment by quintush** [comment]
Hello @michaelruigrok,

Thanks for the feedback.
The intention of the helm unittest is to not connect to a server context, so we can ensure all configuration can be controlled with the test.

With the current kubernetesProvider setup it seems I'm breaking that promise.

Will check on how to fix it.

Greetings,
@quintush

**Comment by michaelruigrok** [comment]
I've also just noticed that namespaced schemes require you to specify a namespace, it doesn't default to "NAMESPACE" as `release.namespace` does. Let me know if you would like a second issue for this, thanks!

before:
```
  objects:
    - kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: default
 ```
 
 after:
 ```
  objects:
    - kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: default
        namespace: NAMESPACE
 ```
