### ISSUE TITLE
Testing values of labels containing / is impossible

### ISSUE THREAD

**Issue by alfsch** [helm-unittest/helm-unittest#382]
Currently I want to check the value of the label

`install.operator.istio.io/owning-resource: argo-cd`

contained in daemonset

```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: istio-cni-node
  namespace: istio-cni
  labels:
    k8s-app: istio-cni-node
    release: istio-cni
    istio.io/rev: default
    install.operator.istio.io/owning-resource: argo-cd
    operator.istio.io/component: "Cni"
```

I'll do this with the following assertion

```
  asserts:
  - equal:
      path: metadata.labels.[install.operator.istio.io/owning-resource]
      value: argo-cd
```

All I get is the following error:

```
		- asserts[0] `equal` fail
			Template:	istio/charts/cni/templates/daemonset.yaml
			DocumentIndex:	0
			Error:
				child name missing at position 16, following ".labels."
```

Is there a workaround for this?
