### ISSUE TITLE
unable to render values of helper template (deploy_targets) values under helm unit test testcase values 

### ISSUE THREAD

**Issue by dayananda30** [helm-unittest/helm-unittest#396]
Getting Error: template: my-chart/templates/deployment.yaml:5:20: executing "my-chart/templates/deployment.yaml" at <include "deploy_targets" .>: error calling include: template: no template "deploy_targets" associated with template "gotpl" while running helm unittest .

my-chart/templates/deployment.yaml

```
{
{- if eq .Values.deployRegion "Default" }}
{{- else }}
{{- $deployRegion := required “deployRegion value is required" .Values.deployRegion }}
{{- $alldeployments := include “deploy_targets" . | fromYaml }}
{{- $context := . }}
{{- range $region, $clusters := $alldeployments.clusters.regions }}
  {{- if eq $region $deployRegion }}
    {{- range $clusters }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: {{ $context.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      annotations:
        app: my-deployment
      labels:
        app: my-deployment
    spec:
      containers:
      - name: app: my-deployment
        image: xyz:latest
        imagePullPolicy: Always
```
        

templates/inventory/deploy_targets.yaml

```
{{- define “deploy_targets" -}}
clusters:
  regions:
    region1:
      - name: region1
        datacenter: region1
        addr: 1.1.1.1
        promPort: 1111
    region2:
      - name: region2
        datacenter: region1
        addr: 1.1.1.1.
        promPort: 1111
{{- end -}}
```
        
       
my testfile look like 

```
suite: Test Deployment
templates:
  - deployment.yaml

tests:
  - it: should skip deployment for Default region
    set:
      deployRegion: Default
    asserts:
      - hasDocuments:
          count: 0

  - it: should create deployment for specified region
    set:
      deployRegion: "region1"
      replicas: 2
      images:
        xxx:
          secondary: false
      imagePullPolicy: Always
      deploy_targets:
        clusters:
          regions:
              region1:
                - name: region1
                  datacenter: region1
                  addr: 1.1.1.1
                  promPort: 1111
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          kind: Deployment
      - isAPIVersion:
          apiVersion: apps/v1
```
 
 
 I am passing deploy_targets values under set directive but still it is failing. Kindly help on this.
 Let me know if there is any workaround for the above scenario.
