### ISSUE TITLE
chart object cannot be overwritten in the tests

### ISSUE THREAD

**Issue by afalhambra-hivemq** [helm-unittest/helm-unittest#412]
I'm just trying to overwrite the `chart` object I have defined at the testsuite level in for a particular test. For example:

```yaml
suite: My testsuite
templates:
  - my-template.yaml
release:
  name: -my-release-name
  namespace: my-namespace
chart:
  appVersion: 1.0.0
  version: 0.0.1
  
tests:

  - it: override chart version and appVersion
    chart:
      appVersion: 2.0.0
      version: 0.2.0
    asserts:
      - equal:
          path: spec.version
          value: 0.2.0
      - equal:
          path: spec.appVersion
          value: 2.0.0
```

From the above I would expect the chart version and the appVersion to be the ones defined within the test, but instead these values are remain with the ones defined at the top root element chart.
