### ISSUE TITLE
capabilities.apiVersions cannot be unset

### ISSUE THREAD

**Issue by afalhambra-hivemq** [helm-unittest/helm-unittest#413]
Would be nice to have the possibility to unset the list of elements set at the `capabilities.apiVersions`. Currently there is no option to do so, so we need to specify the list of `apiVersions` to use in each of the tests defined for a particular testsuite.
For example:

```yaml
suite: MyTemplate test
templates:
  - servicemonitor.yaml
capabilities:
  apiVersions:
    - monitoring.coreos.com/v1
tests:
    
  - it: with monitoring disabled, ServiceMonitor not created
    capabilities:
      apiVersions:
    asserts:
      - hasDocuments:
           count: 0  
```
