### ISSUE TITLE
Helm unit test $.Template.BasePath behaviour does not match Helm

### ISSUE THREAD

**Issue by ivankatliarchuk** [helm-unittest/helm-unittest#426]
Given

Folder structure

```
├── Chart.yaml
├── charts
├── templates
│   ├── parent-configmap.yaml
│   └── parent-deployment.yaml
├── tests
│   ├── __snapshot__
│   └── parent_test.yaml
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  annotations:
    checksum/configmap: {{ include (print $.Template.BasePath "/parent-configmap.yaml") . | sha256sum }}
spec:
  replicas: 3
```

And

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2022-02-18T18:52:05Z
  name: game-config
  namespace: default
data:
  game.properties: |
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
```

Test
```yml
suite: Parent test
templates:
  - parent-deployment.yaml
tests:
  - it: should render deployment
    asserts:
      - hasDocuments:
          count: 1
```

I'd like to test `metadata.annotations["checksum/configmap"]` but for not need at least test not to fail.

Test fails with 

> - should render deployment
		Error: template: chart/templates/parent-deployment.yaml:6:27: executing "chart/templates/parent-deployment.yaml" at <include (print $.Template.BasePath "/parent-configmap.yaml") .>: error calling include: template: no template "chart/templates/parent-configmap.yaml" associated with template "gotpl"

Example gitlab-runner helm chart template https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/templates/deployment.yaml?ref_type=heads#L40

Helm generates templates without any issues

**Comment by ivankatliarchuk** [comment]
Same for sub-charts. Example structure

```
├── Chart.yaml
├── charts
│   └── with-sub-chart
│       ├── Chart.yaml
│       └── templates
│           ├── child-configmap.yaml
│           └── child-deployment.yaml
├── templates
│   ├── parent-configmap.yaml
│   └── parent-deployment.yaml
├── tests
│   ├── __snapshot__
│   ├── parent_test.yaml
│   └── with-sub-chart_test.yaml
└── values.yaml
```

![Screenshot 2024-09-29 at 09 38 29](https://github.com/user-attachments/assets/bf1567df-7865-481d-bdc9-8426331fca64)

Reproduced here https://github.com/ik-workshop/helm-unittests-issues/tree/master/issue-426

**Comment by quintush** [comment]
Hello @ivankatliarchuk 

Please look at https://github.com/helm-unittest/helm-unittest/issues/293 for the solution.

Greetings
@quintush

**Comment by ivankatliarchuk** [comment]
Yeah. This works thank you

Successful test

```yml
suite: Subchart test
templates:
  - charts/with-sub-chart/templates/child-configmap.yaml
  - charts/with-sub-chart/templates/child-deployment.yaml
tests:
  - it: should render deployment
    template: charts/with-sub-chart/templates/child-deployment.yaml
    documentIndex: 0
    asserts:
      - isKind:
            of: Deployment
      - hasDocuments:
          count: 1
      - equal:
          path: metadata.annotations["checksum/configmap"]
          value: "b8a30e9312cc4971949c1a55fa21f8d1d700a8267b11dc84ee98998471526d2f"
```

Dunno. Probably worth to add an end-2-end example to cover this case?
