### ISSUE TITLE
Is there any option to reuse tests section across several testsuite

### ISSUE THREAD

**Issue by afalhambra-hivemq** [helm-unittest/helm-unittest#429]
Hello,
We're currently running quite a few unit tests in our Helm charts, and sometimes we need to run the same tests against a different combination of values defined at a testsuite level. 

For example:
```yaml
suite: HiveMQ Platform ConfigMap tests
templates:
  - hivemq-configuration.yml
  - hivemq-custom-resource.yml
release:
  name: test-hivemq-platform
  namespace: test-hivemq-platform-namespace
chart:
  version: 0.0.1
  appVersion: 1.0.0
tests:

  - it: my-it-1
    asserts:
    ...
  - it: my-it-2
    asserts:
    ... 
  - it: my-it-3
    asserts:
    ... 
```

Would be nice, if I could reuse the whole section under the `tests` for a different `testsuite`, by for example specifying a file containing the base tests set, so I don't need to copy and paste the whole section of `tests` for a different `testsuite`. Not sure if this is already available somehow?
