### ISSUE TITLE
With latest Helm unittest version 0.6.2 - `equalRaw` assertion is no longer working

### ISSUE THREAD

**Issue by afalhambra-hivemq** [helm-unittest/helm-unittest#431]
After latest release of Helm unittest yesterday - 0.6.2, there seems to be a regression, as the `equalRaw` assertion is throwing false positive errors in the unit tests we have.
For example:

```yaml
  - it: with default values
    asserts:
      - equalRaw:
          value: |
            -----
            HiveMQ Platform release "test-hivemq-platform" installed in namespace "test-hivemq-platform-namespace"
            
            Documentation can be found here: https://docs.hivemq.com/hivemq-platform-operator/index.html
            -----
```

With latest version, it's now failing with below:
```
        - with default values

                - asserts[0] `equalRaw` fail
                        Template:       hivemq-platform/templates/NOTES.txt
                        Expected to equal:
                                |-
                                  -----
                                  HiveMQ Platform release "test-hivemq-platform" installed in namespace "test-hivemq-platform-namespace"
                                
                                  Documentation can be found here: https://docs.hivemq.com/hivemq-platform-operator/index.html
                                  -----
                        Actual:
                                |2
                                  ---
                                  --
                                  HiveMQ Platform release "test-hivemq-platform" installed in namespace "test-hivemq-platform-namespace"
                                
                                  Documentation can be found here: https://docs.hivemq.com/hivemq-platform-operator/index.html
                                  ---
                                  --
                        Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,4 @@
                                -|-
                                -  -----
                                +|2
                                +  ---
                                +  --
                                   HiveMQ Platform release "test-hivemq-platform" installed in namespace "test-hivemq-platform-namespace"
                                @@ -5,3 +6,4 @@
                                   Documentation can be found here: https://docs.hivemq.com/hivemq-platform-operator/index.html
                                -  -----
                                +  ---
                                +  --
```

You can reproduce this by your own by:

1. With Helm unittest 0.6.2, clone the HiveMQ Helm charts repo: `git clone https://github.com/hivemq/helm-charts.git`
2. Running `helm unittest ./charts/hivemq-platform -f './tests/**/*_test.yaml'` locally.
