### ISSUE TITLE
helm unittest for configmap data 

### ISSUE THREAD

**Issue by cp319391** [helm-unittest/helm-unittest#435]
our ConfigMap 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: istio-cni-config
data:
  REPAIR_DELETE_PODS: "true"
  REPAIR_REPAIR_PODS: "true" 
```
  
We need to write a test if the value for `REPAIR_DELETE_PODS: `  is set `true`

tried below 
```
- it: test configmap
  templates: 
  - charts/cni/templates/configmap-cni.yaml
  values: *localValues
  asserts:
  - contains:
      path: data
      content:
        name: REPAIR_DELETE_PODS
        value: "true" 
```
it gives below error 
```
  Template:       istio/charts/cni/templates/configmap-cni.yaml
                          DocumentIndex:  0
                          Error:
                                  expect 'data' to be an array, got:
                                  REPAIR_DELETE_PODS: "true"
                            
```
also we tried different asserts like `matchRegex` and `equal` and got kind of similar error. 

What will be the correct way to achieve this ?
