### ISSUE TITLE
Support for overriding .Chart.IsRoot

### ISSUE THREAD

**Issue by Angelin01** [helm-unittest/helm-unittest#449]
**Is your feature request related to a problem? Please describe.**
We have a few charts that are used as "generic charts". One simply imports them as a dependency, like so:
```yaml
dependencies:
  - repository: https://repository.example.com/helm/
    name: simple-rest
    version: "0.1.2"
    alias: my-app
```

And fills the values:
```yaml
my-app:
  image:
    repository: my-app
```

Simple enough!

We also have test coverage on these. However, we have a few functions that rely on `.Chart.IsRoot` that come from a library chart. These detect if they are being used in a subchart (like one of these generic charts) and they change their behavior accordingly, like slightly adjusting labels and such.

To test for these, we have to make a "dummy chart" to use our own chart as a dependency, making the process slightly more convoluted than it needs to be: one needs to make sure they ran `helm dependency update` before tests, slightly less generic CI, you get the idea.

**Describe the solution you'd like**
I am not sure if it is easy, or even viable, but we can already override some contents from the Chart object: version and appVersion. Being able to also override `IsRoot` might _just_ be enough to "trick" the chart into complying with tests more easily, avoiding the necessity for a dummy parent chart, and making the tests as easy as running `helm unittest`.

However, I have no idea of the possible side effects of this change, or if it even is possible.

**Describe alternatives you've considered**
Only the dummy chart idea, above.

**Comment by ivankatliarchuk** [comment]
Is there a publicly available example somewhere? Could you share a full example with template, Chart.yaml and a suite? 

I'm struggling with unittest and `helm dependency update` as well. This definitely needs a new flag. 

But in regards .Chart.IsRoot not sure, there are probably ways to trick/fake call to some commands. Need some sort of investigation here

**Comment by Angelin01** [comment]
@ivankatliarchuk 
> Is there a publicly available example somewhere? Could you share a full example with template, Chart.yaml and a suite?

Sorry for the delay replying, I was in a vacation far far away from my computer.

I unfortunately can't share a full example as it's one of my clients' code, however I can share a similar structure. Here is a setup for testing a library chart which uses a dummy chart for testing:

```
.
├── Chart.yaml
├── templates
│   ├── _affinities.tpl
│   ├── _images.tpl
│   ├── _labels.tpl
│   └── _names.tpl
└── tests
    └── dummy-chart
        ├── Chart.lock
        ├── Chart.yaml
        ├── templates
        │   ├── affinities.yaml
        │   ├── images.yaml
        │   ├── labels.yaml
        │   └── names.yaml
        ├── tests
        │   ├── affinities_test.yaml
        │   ├── images_test.yaml
        │   ├── labels_test.yaml
        │   ├── names_test.yaml
        └── values.yaml
```

In the dummy-chart, we add the main chart as a dependency:
```yaml
apiVersion: v2
name: dummy-chart
description: Dummy chart to test main-chart
type: application
version: 0.0.0
dependencies:
  - repository: file://../..
    name: main-chart
    version: "*"
```

The dummy chart templates are simple includes, like this example for `tests/dummy-chart/templates/names.yaml`:
```yaml
chartName: {{ include "main-chart.names.name" . }}
fullChartName: {{ include "main-chart.names.fullname" . }}
chartNameAndVersion: {{ include "main-chart.names.chart" . }}
serviceAccountName: {{ include "main-chart.names.serviceAccount" . }}
```

which you can then run tests against normally, here is an example:
```yaml
# tests/dummy-chart/tests/names_test.yaml
suite: names test

templates:
  - names.yaml

tests:
  - it: given unset nameOverride then chart name should expand to just just Chart Name
    asserts:
      - equal:
          path: chartName
          value: dummy-chart
```

One detail is that, when running the tests, you **MUST** run `helm dependency build` first, for the dummy-chart to update its dependency on the main chart, so my test run command is actually this:

```shell
helm dependency build --skip-refresh tests/dummy-chart && helm unittest tests/dummy-chart
```

Maybe this can be avoided with symlinks or other similar tricks.
Repeat the nesting, as in, more dummy-charts inside other charts to validate as much as you like.

As for how this is relevant to this issue, I think it's obvious that being able to control `.Chart.IsRoot` would be nice, but it is set individually for each dependency, which is why I understand it might be hard to actually override.
