### ISSUE TITLE
Chart root value files added by default without the option to override this behaviour

### ISSUE THREAD

**Issue by ivankatliarchuk** [helm-unittest/helm-unittest#453]
**Describe the bug**

The chart have a case when the current template logic for configuring the PDB needs adjustments to handle cases where only one of minAvailable or maxUnavailable is provided. Additionally, the tests could be improved to better reflect the expected behavior. But `minAvailable` is set in root chart values, and in tests the only way to disable it is to unset explicitly in tests. Would be nice to have a way to disable root value files for tests. Probably not a bug but a feature request.

**To Reproduce**

Example template

```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "gitlab-runner"
  namespace: "gitlab-ns"
spec:
  {{- if not .Values.managerPdb -}}
  {{ fail "Error: At least one managerPdb.minAvailable or managerPdb.maxUnavailable must be set." }}
  {{- end -}}
  {{- $hasMinAvailable := hasKey .Values.managerPdb "minAvailable" -}}
  {{- $hasMaxUnavailable := hasKey .Values.managerPdb "maxUnavailable" -}}
  {{- if and $hasMinAvailable $hasMaxUnavailable }}
  {{ fail "Error: One of managerPdb.minAvailable or managerPdb.maxUnavailable must be set." }}
  {{- else if $hasMinAvailable }}
  minAvailable: {{ .Values.managerPdb.minAvailable | quote }}
  {{- else if $hasMaxUnavailable }}
  maxUnavailable: {{ .Values.managerPdb.maxUnavailable | quote }}
  {{- end }}
```

Example root value files content
```
managerPdb:
  minAvailable: "50%"
```

Example template

```
suite: Test PodDisruptionBudget
release:
  name: gitlab-runner
  namespace: gitlab-ns
templates:
  - pod-disruption-budget.yaml
tests:
  - it: should be rendered correctly with default config (set to minAvailable)
    set:
      managerPdb:
        minAvailable: "50%"
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: PodDisruptionBudget
      - isSubset:
          path: spec
          content:
            minAvailable: "50%"
            selector:
              matchLabels:
                app: gitlab-runner
      - equal:
          path: metadata.name
          value: gitlab-runner
      - equal:
          path: metadata.namespace
          value: gitlab-ns

  - it: should contain the correct spec when using maxUnavailable config
    set:
      managerPdb:
        minAvailable:
        maxUnavailable: "90%"
    asserts:
      - isSubset:
          path: spec
          content:
            maxUnavailable: "90%"
            selector:
              matchLabels:
                app: gitlab-runner
```

For tets to pass, minAvailable need to be explicitly unset. Is this a correct behaviour?

**Expected behavior**
Not very clear where default values from root file added by default. Excepcted behaviour could be at least to provide a way to unset root values

**Desktop (please complete the following information):**
 - OS: iOS, Docker
 - Plugin Version 0.6.3

**Additional context**

**Comment by jvmdc** [comment]
Helm always uses the `values.yaml` file as the default value, so not sure why you'd want to exclude it.


![image](https://github.com/user-attachments/assets/5c53e8cc-e89a-465a-bde7-df5f64f2e92c)
Source: https://helm.sh/docs/chart_template_guide/values_files/

**Comment by quintush** [comment]
Hello @ivankatliarchuk ,

The ability to clean a default value is already available in the solution.
Only make sure the value is explicitly set with null, so like this:

```yaml
managerPdb:
  minAvailable: null
```

Within the helm-unittest all values are simply overridden, but at the end the values are send to helm for rendering the chart (just like helm template) where helm itself will remove the nullable fields.

Greetings,
@quintush

**Comment by ivankatliarchuk** [comment]
Yeah. This is a testing framework, so it should be possible to exclude certain things completely. I have dozens of umbrella charts and need to test them in isolation quite often. Quite often I have no access to underlying helm charts, and sometimes it's something like.

In our platform we write umbrella controllers to abstract certain things completely

Root chart
```yml
name: top-level
appVersion: "991"
dependencies:
- name: chart-a-that-contains-dependencies
  version: 1.0.0
  repository: https://kadfasdfasdf
- name: chart-b-that-contains-dependencies
  version:  1.0.0
  repository: https://kadfasdfasdf
```

Another chart
```yml
name: chart-a-that-contains-dependencies
appVersion: "991"
dependencies:
- name: chart-a-dependency
  version: 1.0.0
  repository: https://kadfasdfasdf
- name: chart-b-dependency
  version:  1.0.0
  repository: https://kadfasdfasdf
```

Not a critical feature, but quite nice sometimes to disable native values.yml files
