### ISSUE TITLE
`set` to patch an array replace instead of merge

### ISSUE THREAD

**Issue by babs** [helm-unittest/helm-unittest#471]
**Describe the bug**
Using `set`  to patch an element of an array erase the array instead of merging it:

```yaml
set:
  anArray[1].attribute: new attribute1
```

**To Reproduce**
[full demo will follow]

`values.yaml`
```yaml
anArray:
- name: value0
  attribute: attribute0
- name: value1
  attribute: attribute1
```

patch
```yaml
set:
  anArray[1].attribute: new attribute1
```

expected
```yaml
anArray:
- name: value0
  attribute: attribute0
- name: value1
  attribute: new attribute1
```

got
```yaml
anArray:
- null
- attribute: new attribute1
```

**Expected behavior**

When patching an array using `set` option the array is not deep merged but fully replaced

**Desktop (please complete the following information):**
 - OS: Linux
 - Plugin Version: 0.6.3
