### ISSUE TITLE
How to check all documents are of a given kind?

### ISSUE THREAD

**Issue by V02460** [helm-unittest/helm-unittest#478]
Asserting the `kind` of all documents in a test sounds like an easy thing to do, but I was not able to get it working.

Specifically in my case, I want to ensure that all documents from the folder `network-policies` have the type `NetworkPolicy`. The tricky part for me is that each template file can render anything from 0 to n documents. Please help? 🙂

**Comment by ivankatliarchuk** [comment]
Have you found an answer?

To better help with the question, worth to provide an example helm chart or link to public chart if any.

There are multiple options. Example

```
  - it: should use root values file with set few attributes in test
    templates:
    - templates/network-policies/*.yaml 
    asserts:
      - containsDocument:
          kind: NetworkPolicy
          apiVersion: v1
      - contains:
           path: kind
           value:  NetworkPolicy
         count: 0 to infinity
       - equal:
          path: kind
          value: NetworkPolicy
       - isKind:
         of: NetworkPolicy
```

**Comment by V02460** [comment]
Thank you for replying! Sadly, the given suggestions all don’t work. They fail for cases of a template not producing a document:

1. ```
   DocumentIndex:  0
   Expected to contain document:
           Kind = NetworkPolicy, apiVersion = networking.k8s.io/v1
    ```
2. Is not valid Syntax for an assertion.
3. ```
   Path:   kind
   Expected to equal:
           NetworkPolicy
   Actual:
           no manifest found
   Diff:
           --- Expected
           +++ Actual
           @@ -1,2 +1,2 @@
           -NetworkPolicy
           +no manifest found
   ```
4. ```
   Expected to be kind:
           NetworkPolicy
   Actual:
           no manifest found
   ```

**Comment by ivankatliarchuk** [comment]
You may need to share full tests, as too little information provided.

**Comment by ivankatliarchuk** [comment]
There is as well document selector

Worth to check the docs https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md, as there are quite few different options, as well there is bunch of examples https://github.com/helm-unittest/helm-unittest/tree/main/test/data

```yml
  asserts:
      - equal:
          path: metadata.namespace
          value: ***
        documentSelector:
          skipEmptyTemplates: true/false
```

**Comment by V02460** [comment]
> There is as well document selector

This is some progress! :) Using `documentSelector` does *nearly* the right thing: with `matchMany` and `skipEmptyTemplates` enabled, it seems to properly all-quantify the documents.

The remaining problem is that I am forced to additionally give the `path` and `value` options, but there is no reasonable way I can set them. I don’t want to select a document based on a specific value, but instead I need all documents selected.


> You may need to share full tests, as too little information provided.

```yaml
# Should pass
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
...

# Should pass
---
...

# Should fail
---
apiVersion: v1
kind: Secret
...
```

**Comment by ivankatliarchuk** [comment]
Not exactly, but could be related to this issue https://github.com/helm-unittest/helm-unittest/issues/590

**Comment by mysiki** [comment]
Hey,

In addition, can be great to do documentSelector without value, or with regex accepted value. In my case, I want to validate that all object of apiVersion "*.aws.upbound.io/*" have specific label. I do it by cheating and using json path that match another labels that I not is always present (not really strict solution). 

But I have another case, for all this apiVersion ("*.aws.upbound.io/*") if the key "spec.forProvider.tags" exist I want to test the content (tags is not always present in this apiVersion objects - 90% present).

Note : I run this test over all templated file (because more simple, because don't want to forgot file and because can be done by my CI as standard chart validation)

```
templates:
  - "**/templates/**/*.yaml"
```

Example for the first one : 

Yaml 
```yaml
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: 'local-kms-fsx-iam-role-local'
  labels:    
    app.kubernetes.io/instance: 'ads'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'fsx'
    app.kubernetes.io/version: '1.0.0'
    xxx.com/environment: 'local'
  annotations:
    meta.xxx.io/external-name-managed: 'from-inventory'
```

test : Work because by standard (and previous test) every object have "xxx.com/environment" label.
```yaml
  - it: Crossplane external-name-managed annotation
    documentSelector:
      path: $[?(@.apiVersion =~ /.*\.aws\.upbound\.io\/.*$/)].metadata.labels["xxx.com/environment"]
      value: local
      skipEmptyTemplates: true
      matchMany: true
    asserts:
      - exists:     
          path: metadata.annotations["meta.xxx.io/external-name-managed"]
```


But for my second case, I cannot scope because "tags" can be present or not. And if it present, I want to test.

So I would like something like :
```
  - it: Crossplane external-name-managed annotation
    documentSelector:
      path: apiVersion 
      value: ".*\.aws\.upbound\.io\/.*$"
# or       value: "*.aws.upbound.io/*"
      skipEmptyTemplates: true
      matchMany: true
```

Or maybe to avoid regression or big change in existing test (no value key means match all): 
```
  - it: Crossplane external-name-managed annotation
    documentSelector:
      path: $[?(@.apiVersion =~ /.*\.aws\.upbound\.io\/.*$/)].metadata.name
      skipEmptyTemplates: true
      matchMany: true
```

Can also imagine to add "regexValue" in addition to "value" key ... 

lot of idea but no skill to PR it, sorry ...
