### ISSUE TITLE
Set Subcharts properties that are not within the Values file

### ISSUE THREAD

**Issue by jdiegosierra** [helm-unittest/helm-unittest#479]
**Is your feature request related to a problem? Please describe.**
I'm setting a label that I want to test:

`
helper.version: {{ (index .Subcharts "common-helpers-helm-library").Chart.Version }}
`

So I would like to overwrite the subchart properties that are not within the Values file:

**Describe the solution you'd like**
```yaml
  - it: test
    set:
      common-helpers-helm-library:
        Chart:
          Version: 1.3
```
