### ISSUE TITLE
Include tests from dependencies

### ISSUE THREAD

**Issue by Fabccc** [helm-unittest/helm-unittest#488]
**Is your feature request related to a problem? Please describe.**
I have to trick helm unittest when i want to test a chart for an application and it's common dependencies, for example a chart with a bunch of utils and than a chart use it.

**Describe the solution you'd like**
It could be interesting to include the tests from dependencies, so that tests run against other values.

**Describe alternatives you've considered**
Using scripts to re-arrange helm chart in the CI to move tests from the dependent chart to the target chart

**Comment by ivankatliarchuk** [comment]
Hi. Do you mean something like this https://github.com/helm-unittest/helm-unittest/tree/main/test/data/v3/with-subsubcharts? Without examples case is a bit tricky to understand

**Comment by ivankatliarchuk** [comment]
Got it. Yep, I'm aware of `bitnamy` approach. Most likely this is the [chart](https://github.com/bitnami/charts/tree/main/bitnami/common) e.g. chart of type [library](https://helm.sh/docs/topics/library_charts/#helm)

**Comment by ivankatliarchuk** [comment]
I'll submit an example at some point. Looks like maintaner is away for a while.

This is how structure looks like in my case for library charts
```
.
├── Chart.yaml
├── README.md
├── helpers.mk
├── templates
│   ├── _annotations.tpl
│   ├── _dns.tpl
│   ├── _labels.tpl
│   ├── _names.tpl
│   ├── _utils.tpl
│   └── _validations.tpl
└── tests
    └── chart
        ├── Chart.yaml
        ├── templates
        │   ├── dns.yaml
        │   ├── host.yaml
        │   ├── ingressroute.yaml
        │   ├── pod.yaml
        │   └── servertransport.yaml
        └── tests
            └── unit
                ├── __snapshot__
                ├── dns_test.yaml
                ├── host-access_test.yaml
                ├── ingressroute_test.yaml
                ├── metadata_test.yaml
                └── servertransport_test.yaml
```

Root chart.yml content
```
annotations:
  category: infrastructure
apiVersion: v2
appVersion: 1.0.0
version: 1.0.0
type: library
```

test `Chart.yaml`

```
apiVersion: v2
name: test-common
description: required to test library chart
type: application
version: "1"
dependencies:
- name: common
  version: "1.x.x"
  repository: "file://../../../common"
```

example content for file `common/tests/chart/templates/pod.yaml`

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "common.names.name" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

How to execute `makefile`
```
common-test: ## Run Common unit tests
	@helm dependency build common/tests/chart
	@helm unittest -f 'tests/unit/*.yaml' --color common/tests/chart
```

Agree, worth to add to examples. As helm unittest can be improved
