### ISSUE TITLE
decodeBase64 option adds literal YAML multi-line string syntax

### ISSUE THREAD

**Issue by jennydaman** [helm-unittest/helm-unittest#494]
**To Reproduce**

Create a helm chart with the template:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: foo
data:
  greeting: 'aGVsbG8K'
```

And with the test:

```yaml
tests:
  - it: should be "hello"
    asserts:
      - equal:
          path: data.greeting
          value: hello
          decodeBase64: true
          # value: 'aGVsbG8K'
```

**Expected behavior**

Test passes

**Actual Behavior**

```
	- should be "hello"

		- asserts[0] `equal` fail
			Template:	pfcon/templates/pman-secrets.yml
			DocumentIndex:	0
			Path:	data.greeting
			Expected to equal:
				hello
			Actual:
				|
				 hello
			Diff:
				--- Expected
				+++ Actual
				@@ -1,2 +1,3 @@
				-hello
				+|
				+  hello
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Plugin Version: I tried both the container image `docker.io/helmunittest/helm-unittest:3.16.1-0.6.3` and version `0.5.2` installed from nixpkgs.
