### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mikolajsobolewski** [helm-unittest/helm-unittest#497]
**Describe the bug**
When i run test scenario i have panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xa0 pc=0x105865ff4]

goroutine 1 [running]:
github.com/helm-unittest/helm-unittest/pkg/unittest.(*TestSuite).polishChartSettings(0x1400044f380?, 0x2b?)
	/home/runner/work/helm-unittest/helm-unittest/pkg/unittest/test_suite.go:313 +0x24
github.com/helm-unittest/helm-unittest/pkg/unittest.ParseTestSuiteFile({0x1400044f380, 0x2b}, {0x140004840b8, 0x7}, 0x0, {0x0, 0x0, 0x0})
	/home/runner/work/helm-unittest/helm-unittest/pkg/unittest/test_suite.go:48 +0x358
github.com/helm-unittest/helm-unittest/pkg/unittest.(*TestRunner).getTestSuites(0x1069d5500, {0x16b56312c, 0xe}, {0x140004840b8, 0x7})
	/home/runner/work/helm-unittest/helm-unittest/pkg/unittest/test_runner.go:153 +0x27c
github.com/helm-unittest/helm-unittest/pkg/unittest.(*TestRunner).getV3TestSuites(0x1069d5500, {0x16b56312c, 0xe}, {0x140004840b8, 0x7}, 0x14000494b40)
	/home/runner/work/helm-unittest/helm-unittest/pkg/unittest/test_runner.go:177 +0x3c
github.com/helm-unittest/helm-unittest/pkg/unittest.(*TestRunner).RunV3(0x1069d5500, {0x14000533a20, 0x14, 0x0?})
	/home/runner/work/helm-unittest/helm-unittest/pkg/unittest/test_runner.go:94 +0xd4
main.RunPlugin(0x1400019e700?, {0x14000533a20, 0x14, 0x16})
	/home/runner/work/helm-unittest/helm-unittest/cmd/helm-unittest/helm_unittest.go:112 +0x2d8
github.com/spf13/cobra.(*Command).execute(0x1069bf0e0, {0x1400003a190, 0x16, 0x17})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x1069bf0e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
	/home/runner/work/helm-unittest/helm-unittest/cmd/helm-unittest/helm_unittest.go:121 +0x24
Error: plugin "unittest" exited with error
```
**To Reproduce**
1. Example helm project
```
---
{{- if .Values.node.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.node.name }}-http
{{- end}}
```
2. Example test scenario
```
suite: test wardend service
templates:
  - service.yaml
tests:
  - it: "should create Service if node is enabled"
    set:
      node:
        enabled: true
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: Service
      - isMatch:
          path: metadata.name
          pattern: ".*-http"
 ```
