### ISSUE TITLE
Execution of a test with a pre-condition

### ISSUE THREAD

**Issue by quangkhainguyen** [helm-unittest/helm-unittest#498]
I have written a Helm Unittest like below: 

```yaml
suite: Application should have PodDisruptionBudget, which guarantees high availability
templates:
  - templates/*.yml
tests:
  - it: ABBL4 deployment should have a proper configuration of `PodDisruptionBudget`
    documentSelector:
      path: kind
      value: PodDisruptionBudget
      skipEmptyTemplates: true
    asserts:
      - exists:
          path: spec.minAvailable

```
This test represents our blue-print and should verify Helm templates from various teams, if their templates match our blue-print.
But we have found out, that it doesn't make sense to run the test of `PodDisruptionBudget` (above) against deployment, which has only 1 replica (under `spec.replicas`). With 1 single replica, high availability is not ensured. 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'application-from-team-a'
spec:
  replicas: '1'
  template:
    spec:
      containers:
        - name: 'main-1'
          image: 'busybox:latest'
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'openshift'
          ports:
            - containerPort: 8080
```

Is there any way to mark a pre-condition like:
when  `spec.replicas` > 1, then the test of `PodDisruptionBudget` should be applied. 

I have read DOCUMENT.md few times, but I don't any answer to my question. Any advice would be appreciated.
