### ISSUE TITLE
`failedTemplate` assertion fails when the error message contains special characters

### ISSUE THREAD

**Issue by afalhambra-hivemq** [helm-unittest/helm-unittest#499]
**Describe the bug**
In our Helm templates we have some scenarios where we explicitly fail the Helm installation as below:
```
{{- fail (printf "\n`runAsNonRoot` is set to `true` but `runAsUser` is set to `0` (root)") }}
```
And in our test suite, we have the following assertion:
```yaml
    asserts:
      - failedTemplate:
          errorPattern:
            `runAsNonRoot` is set to `false` but `runAsUser` is not set to `0` \(root\)
```            
Running the unit test, it fails as below:
```bash
 FAIL   charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml
        - Execution Error: 
                yaml: line 362: found character that cannot start any token

### Error:  yaml: line 362: found character that cannot start any token

Charts:      1 failed, 1 errored, 0 passed, 1 total
Test Suites: 1 failed, 1 errored, 0 passed, 1 total
Tests:       0 passed, 0 total
Snapshot:    0 passed, 0 total
Time:        16.051375ms

Error: plugin "unittest" exited with error
```
The only workaround possible for us to simply add the following `|-` to the assertion as below:
```yaml
    asserts:
      - failedTemplate:
          errorPattern: |-
            `runAsNonRoot` is set to `false` but `runAsUser` is not set to `0` \(root\)
```
This seems to happen only when the error message starts with some special characters like ` in this case.

**To Reproduce**
1. git clone https://github.com/hivemq/helm-charts.git && cd helm-charts
2. Remove the `|-` from the `hivemq_operator_deployment_test.yaml` file on line [363](https://github.com/hivemq/helm-charts/blob/develop/charts/hivemq-platform-operator/tests/hivemq_operator_deployment_test.yaml#L363).
3. Run `helm unittest ./charts/hivemq-platform-operator -f './tests/**/*_test.yaml'`

**Expected behavior**
Regardless of the first error message character, like in this case, the assertion for the `failedTemplate` should work.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Plugin Version 0.6.3

**Additional context**
This works fine when the starting character is not a special character such as `.

**Comment by ivankatliarchuk** [comment]
I'm not sure what he issue exactly, but

```
    asserts:
      - failedTemplate:
          errorPattern: |-
            `runAsNonRoot` is set to `false` but `runAsUser` is not set to `0` \(root\)
```
means pretty much same as
```
    asserts:
      - failedTemplate:
          errorPattern: "`runAsNonRoot` is set to `false` but `runAsUser` is not set to `0` \(root\)"
```

So not sure if the issue is with backtics

Try something like
```
asserts:
      - failedTemplate:
          errorPattern: |-
             `runAsNonRoot` is set to `true` but `runAsUser` is set to `0` (root)
```
