### ISSUE TITLE
JSONPath on evaluation on map key

### ISSUE THREAD

**Issue by quangkhainguyen** [helm-unittest/helm-unittest#503]
**Describe the bug**
I have written a helm unittest, which verifies that

1. `spec.template.spec.nodeSelector` path should exist and
2. a key value either `"node-role.kubernetes.io/mem-optimized" : ""` or `"node-role.kubernetes.io/cpu-optimized"` should be also present.

An example `deployment.yaml` may look like as below

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
     spec:
        nodeSelector:
            node-role.kubernetes.io/mem-optimized: "" 
          # node-role.kubernetes.io/cpu-optimized: ""  <--- it could be also a cpu-optimized
```

```yaml
suite: Testsuite NodeSelector
templates:
  - deployment.yaml
tests:
  - it: Deployment should define nodeSelector for deployments
    documentSelector:
      path: kind
      value: Deployment
      skipEmptyTemplates: true
    asserts:
      - exists:
          path: spec.template.spec.nodeSelector
      - exists:
          path: spec.template.spec.nodeSelector[?(@.property =~ /node-role.kubernetes.io\/(mem|cpu)-optimized/)]
```

Running this unittest against the deployment above gives me following error message:
```
  - Deployment should define nodeSelector for deployments

                - asserts[1] `exists` fail
                        Template:       reference/templates/deployment.yaml
                        DocumentIndex:  0
                        Path:   spec.template.spec.nodeSelector[?(@.property =~ /node-role.kubernetes.io\/(mem|cpu)-optimized/)] expected to exists
```

I have tried evaluating `$.spec.template.spec.nodeSelector[?(@property=~"node-role.kubernetes.io/(mem|cpu)-optimized")]`  on jsonpath.com with
```json
{
    "apiVersion" : "apps/v1",
    "spec" : {
        "template" : {
            "spec": {
                "nodeSelector" :{
                    "node-role.kubernetes.io/mem-optimized" : ""
                }
            }
        }
    }
}
```
This works fine. 

Did I make something wrong in my unittest? Thank you in advance!
