### ISSUE TITLE
ns_test.yaml seems to be a YAML file, but expected a gzipped archive

### ISSUE THREAD

**Issue by sebdau** [helm-unittest/helm-unittest#518]
**Describe the bug**
With more than one test.yaml file selected via -f this error is shown:

`### Error:  file '/mnt/d/testdata/helmut/tests/ns_test.yaml' seems to be a YAML file, but expected a gzipped archive`

**To Reproduce**
1. Example helm project

- templates/cm.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: {{ .Values.ns }}
```

- templates/cm2.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm2
  namespace: {{ .Values.ns }}
```

- tests/ns_test.yaml
```
suite: chart tests
templates:
  - templates/cm.yaml

tests:
  - it: should have namespace
    asserts:
      - equal:
          path: metadata.namespace
          value: testns
```

- tests/ns2_test.yaml
```
suite: chart tests
templates:
  - templates/cm2.yaml

tests:
  - it: should have namespace2
    asserts:
      - equal:
          path: metadata.namespace
          value: testns
```

- values.yaml
`ns: testns`

3. Example test scenario

helm unittest -f /mnt/d/testdata/helmut/tests/*.yaml -v /mnt/d/testdata/helmut/values.yaml -d /mnt/d/testdata/helmutout/chart.tgz

**Expected behavior**
Both tests should be executed without failure

***Failure***

```
### Error:  file '/mnt/d/testdata/helmut/tests/ns_test.yaml' seems to be a YAML file, but expected a gzipped archive

time="2024-12-20T16:39:01+01:00" level=debug msg="file-patterns: [/mnt/d/testdata/helmut/tests/ns2_test.yaml]" files=get-files
time="2024-12-20T16:39:01+01:00" level=debug msg="chart-path: /mnt/d/testdata/helmutout/false-0.1.0.tgz fileset: [/mnt/d/testdata/helmut/tests/ns2_test.yaml]" files=get-files
time="2024-12-20T16:39:01+01:00" level=debug msg="file-patterns: [/mnt/d/testdata/helmut/values.yaml]" files=get-files
time="2024-12-20T16:39:01+01:00" level=debug msg="chart-path:  fileset: [/mnt/d/testdata/helmut/values.yaml]" files=get-files
time="2024-12-20T16:39:01+01:00" level=debug msg="suite '/mnt/d/testdata/helmut/tests/ns2_test.yaml' total parts 1" test-suite=parse-test-suite-file
time="2024-12-20T16:39:01+01:00" level=debug msg="test.chart '{ }" test-suite=polish-chart-settings
time="2024-12-20T16:39:01+01:00" level=debug msg="test.capabilities '{  []}" test-suite=polish-capabilities-settings

### Chart [ false ] /mnt/d/testdata/helmutout/false-0.1.0.tgz

time="2024-12-20T16:39:01+01:00" level=debug msg="suite 'chart tests' total tests 1" test-suite=polish-test-jobs-path-info
time="2024-12-20T16:39:01+01:00" level=debug msg="test.release '{  0 false}" test-suite=polish-release-settings
time="2024-12-20T16:39:01+01:00" level=debug msg="test.capabilities '{  []}" test-suite=polish-capabilities-settings
time="2024-12-20T16:39:01+01:00" level=debug msg="test.chart '{ }" test-suite=polish-chart-settings
time="2024-12-20T16:39:01+01:00" level=debug msg="test 'should have namespace' with total values 1 and [/mnt/d/testdata/helmut/values.yaml]" test-suite=polish-test-jobs-path-info
time="2024-12-20T16:39:01+01:00" level=debug msg="expected chartRoute: false" filterV3Templates=chartRoute
time="2024-12-20T16:39:01+01:00" level=debug msg="expected currentRoute: false" filterV3Templates=currentRoute
time="2024-12-20T16:39:01+01:00" level=debug msg="expected templateToAssert: [templates/configmap2.yaml]" filterV3Templates=templateToAssert
 PASS  chart tests      tests/ns2_test.yaml

Charts:      1 failed, 1 errored, 1 passed, 2 total
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        21.342607ms
```

**Desktop (please complete the following information):**
 - OS: Win11 / WSL / Ubuntu 22
 - helm version
`version.BuildInfo{Version:"v3.16.3", GitCommit:"cfd07493f46efc9debd9cc1b02a0961186df7fdf", GitTreeState:"clean", GoVersion:"go1.22.7"}`
- helm plugin list
```
NAME            VERSION DESCRIPTION
unittest        0.7.0   Unit test for helm chart in YAML with ease to keep your chart functional and robust.
```

**Additional context**
