### ISSUE TITLE
Valid YAML is not process correctly

### ISSUE THREAD

**Issue by kuisathaverat** [helm-unittest/helm-unittest#543]
**Describe the bug**

A valid YAML file is not processed correctly and returns a weird error.

**To Reproduce**
1. Create a helm chart `helm create hello
2. Create a test like this one `hello/tests/deployment_test.yaml`
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/refs/heads/main/schema/helm-testsuite.json
---
suite: Test YAML
templates:
  - deployment.yaml
release:
  name: foo
  namespace: bar
tests:
  - it: Just dummy test
    set:
      name: foo
    asserts:
      - isKind:
          of: Deployment
```
4. Run the test `helm unittest ./hello`
5. The test failed with the following error
```log
 FAIL  	hello/tests/deployment_test.yaml
	- Execution Error: 
		EOF


### Error:  EOF


Charts:      1 failed, 1 errored, 0 passed, 1 total
Test Suites: 1 failed, 1 errored, 0 passed, 1 total
Tests:       0 passed, 0 total
Snapshot:    0 passed, 0 total
Time:        6.969159ms

Error: plugin "unittest" exited with error
````

the issue is related to the two first lines

```yaml
#
---
```

if you change the order it works

```yaml
---
#
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Plugin Version 0.7.1

**Additional context**
