### ISSUE TITLE
0.7.2 breaks checking for multiline errors

### ISSUE THREAD

**Issue by petewall** [helm-unittest/helm-unittest#559]
**Describe the bug**
Since the 0.7.2 update, my tests that check for multiline errors only reports the first line.

**To Reproduce**
I have an example chart with these values:
```yaml
settings:
  name: ""
  fail: false
```
and a single template:
```yaml
{{- if .Values.settings.fail }}
  {{- $msg := list "" "You've set fail to true. This will cause a failure. Please set:" }}
  {{- $msg = append $msg "fail: false" }}
  {{- $msg = append $msg "and try again" }}
  {{- fail (join "\n" $msg) }}
{{- end }}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: {{ .Values.settings.name | default "pod" }}
spec:
  containers:
  - image: nginx
    name: pod
```

Here is my test:
```yaml
---
suite: Test failure message
templates:
  - pod.yaml
tests:
  - it: prints an error message
    set:
      settings:
        fail: "true"
    asserts:
      - failedTemplate:
          errorMessage: |-
            execution error at (failed-chart-test/templates/pod.yaml:5:6): 
            You've set fail to true. This will cause a failure. Please set:
            fail: false
            and try again
```

This test works in 0.7.1, but fails in 0.7.2:
```bash
$ docker run --rm --volume $(pwd)/apps helmunittest/helm-unittest:3.17.0-0.7.1 .

### Chart [ failed-chart-test ] .

 PASS  Test failure message     tests/default_test.yaml

Charts:      1 passed, 1 total
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        35.365208ms

$ docker run --rm --volume $(pwd):/apps helmunittest/helm-unittest .

### Chart [ failed-chart-test ] .

 FAIL  Test failure message     tests/default_test.yaml
        - prints an error message

                - asserts[0] `failedTemplate` fail
                        Template:       failed-chart-test/templates/pod.yaml
                        DocumentIndex:  0
                        Expected to equal:
                                execution error at (failed-chart-test/templates/pod.yaml:5:6): 
                                You've set fail to true. This will cause a failure. Please set:
                                fail: false
                                and try again
                        Actual:
                                You've set fail to true. This will cause a failure. Please set:


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 0 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        33.184209ms
```

Even if I remove the leading "execution error at..." line, it still fails with only one line:

```yaml
$ docker run --rm --volume $(pwd):/apps helmunittest/helm-unittest .

### Chart [ failed-chart-test ] .

 FAIL  Test failure message     tests/default_test.yaml
        - prints an error message

                - asserts[0] `failedTemplate` fail
                        Template:       failed-chart-test/templates/pod.yaml
                        DocumentIndex:  0
                        Expected to equal:
                                You've set fail to true. This will cause a failure. Please set:
                                fail: false
                                and try again
                        Actual:
                                You've set fail to true. This will cause a failure. Please set:


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 0 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        41.252708ms
```

**Expected behavior**
I'd expect multiline errorMessages to compare correctly.

**Desktop (please complete the following information):**
 - OS: MacOS, arm64
 - Plugin Version 0.7.2
