### ISSUE TITLE
Enable documentSelector for hasDocuments asserts

### ISSUE THREAD

**Issue by wiegandf** [helm-unittest/helm-unittest#590]
**Is your feature request related to a problem? Please describe.**
It would be nice to make hasDocuments work with documentSelector. I can see that it's ignored at the moment.

**Describe the solution you'd like**
Either never ignore the documentSelector for hasDocuments or add a flag to enable it. I am not sure if there was a particular reason why it was ignored at the beginning.

**Describe alternatives you've considered**
n/a

**Additional context**
Template under test
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
````

Test suite
```yaml
suite: Test Deployment Resources
templates:
  - templates/deployment.yaml
tests:
  - documentSelector:
      path: metadata.name
      value: green
    asserts:
      - isKind:
          of: Deployment
      - hasDocuments:
          count: 1
  - documentSelector:
      path: metadata.name
      value: green
    asserts:
      - isKind:
          of: Deployment
      - equal:
          path: metadata.name
          value: green
```
