### ISSUE TITLE
Execution Error: Assertion type `greaterOrEqual` is invalid

### ISSUE THREAD

**Issue by TheUnableDeveloper** [helm-unittest/helm-unittest#595]
**Describe the bug**
Hello,
I just started to use this tool and I'm trying to use the "greaterOrEqual" assertion.
But I get this error: "Execution Error: Assertion type `greaterOrEqual` is invalid".
Same for "notGreaterOrEqual".
Schema validation using:
``` # yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json) ```
doesn't show any error

**To Reproduce**
This is my test:

````
- it: static - min replicas = 1
    set:
      micro.assets.replicas: 1
    asserts:
      - isKind:
          of: Deployment
        documentIndex: 1
      - greaterOrEqual:
          path: spec.replicas
          value: 1
````

**Expected behavior**
I should be able to check if spec.replicas is >= 1

**Desktop (please complete the following information):**
 - OS: MacOs 15.1.1 (24B91) Sequoia M1
 - Plugin Version 0.3.1

Thanks
