### ISSUE TITLE
skipEmptyTemplate fails when no matching templates are found

### ISSUE THREAD

**Issue by chlab** [helm-unittest/helm-unittest#604]
**Describe the bug**
I want to assert certain things in templates _if they exist_. For example, if you use an `ExternalSecret`, it must follow certain conventions. If you don't, the test should just quietly be ignored.

This is how I understood `skipEmptyTemplates` so far - if you don't find any matching documents, just skip asserting anything in them. However, the test fails with:

```
Expected to equal:
	<whatever you're asserting>
Actual:
	no manifest found
```

**To Reproduce**
Run a test for something that isn't contained in the chart you're testing against, e.g.:

```
suite: ExternalSecrets
templates:
  - templates/*.y*ml
tests:
  - it: ExternalSecret should use correct target policies
    documentSelector:
      path: kind
      value: ExternalSecret
      skipEmptyTemplates: true
    asserts:
    - equal:
        path: spec.target.creationPolicy
        value: Owner
```

**Expected behavior**
The test 'ExternalSecret should use correct target policies' should not be run or at the least, shouldn't fail.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 15.3.2
 - Plugin Version: 0.8.0

**Additional context**

**Comment by ivankatliarchuk** [comment]
Could you share manifests as well. Fir sucess and failed cases

**Comment by chlab** [comment]
@ivankatliarchuk sure, here's a complete reproduction of the test succeeding and failing, depending on which templates are found: https://github.com/chlab/helmunittest-skipemptytemplates

**Comment by chlab** [comment]
@ivankatliarchuk sure, here's a complete reproduction of the test succeeding and failing, depending on which templates are found: https://github.com/chlab/helmunittest-skipemptytemplates

**Comment by ivankatliarchuk** [comment]
Understood. So desired behaviour, when no templates found is to skip test execution, instead of failing it

```
documentSelector:
      path: kind
      value: ExternalSecret
      skipEmptyTemplates: true
```
