### ISSUE TITLE
Regression: templating an empty value fails

### ISSUE THREAD

**Issue by gilles-gosuin** [helm-unittest/helm-unittest#616]
**Describe the bug**
`Error: template: **REDACTED**/templates/bug-report.yaml:5:23: executing "**REDACTED**/templates/bug-report.yaml" at <.Values.emptyValue>: wrong type for value; expected string; got interface {}`

**To Reproduce**

```yaml
# templates/bug-report.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{- tpl .Values.emptyValue $ | quote }}
```

```yaml
# tests/bug-report_test.yaml
suite: bug-report
templates:
  - bug-report.yaml
tests:
  - it: should not fail
    set:
      emptyValue:
    asserts:
      - matchSnapshot: {}
```

**Expected behavior**
Should not raise an error.

**Desktop (please complete the following information):**
 - OS: macOS
 - Plugin Version: 0.4.4 and later

**Additional context**
Used to work fine in versions 0.4.3 (and probably earlier)

**Comment by ivankatliarchuk** [comment]
Most likely the error handling has changed. I not managed to get to the bottom. If you run `helm template test  chart-regression` on this template, the error exacly it

```sh
Error: template: regression/templates/configmap.yaml:5:23: executing "regression/templates/configmap.yaml" at <.Values.emptyValue>: wrong type for value; expected string; got interface {}
```

We most likely fixed a bug and now helm unit tests mimic helm behaviour as the error is thrown not by unittest but within helm itself.

Out of curiosity, how snapshot looks like?

**Comment by quintush** [comment]
Hello @gilles-gosuin 

Thanks for the feedback.
Like @ivankatliarchuk already mentioned, the helm template command is resulting the same error as the helm unittest.


I would recommend to prevent setting keys without a value.
Best to define a value or at least define the type you expect (similar to the snapshot code where we explicitly identify the 'matchSnapshot' as an object (using {} as value).

Here are some examples that will generate a more stable outcome
``` yaml
  - it: should not fail
    set:
      emptyValue: ""
    asserts:
      - matchSnapshot: {}
```
or
``` yaml
  - it: should not fail
    set:
      emptyValue: ''
    asserts:
      - matchSnapshot: {}
```
or
``` yaml
  - it: should not fail
    set:
      emptyValue: !!str
    asserts:
      - matchSnapshot: {}
```

Greetings,
@quintush
