### ISSUE TITLE
0.8.0 regression: chart version defined in a test leaks in subsequent tests

### ISSUE THREAD

**Issue by afeblot** [helm-unittest/helm-unittest#627]
**Describe the bug**

A `chart.version` defined in a given test leaks in subsequent tests, instead of only applying to the test where it is defined.

**To Reproduce**

`bug/Chart.yaml`
```yaml
apiVersion: v2
appVersion: 0.0.0
description: my unittest bug showcase chart
name: bug
version: 0.0.0
```

`bug/templates/showit.yaml`
```yaml
showit: "{{ $.Chart.Name}}-{{ $.Chart.Version }}"
```

`bug/tests/showit_test.yaml`
```yaml
suite: regression tests
templates:
  - showit.yaml

tests:

  - it: without overridden chart values
    asserts:
      - equal:
          path: showit
          value: "bug-0.0.0"

  - it: with overridden chart values
    chart:
      version: 0.1.0
    asserts:
      - equal:
          path: showit
          value: "bug-0.1.0"

  - it: without overridden chart values FAILS BUT SHOULD NOT
    asserts:
      - equal:
          path: showit
          value: "bug-0.0.0"
```

`helm unittest bug` result:

```
### Chart [ bug ] bug

 FAIL  regression tests bug/tests/showit_test.yaml
        - without overridden chart values FAILS BUT SHOULD NOT

                - asserts[0] `equal` fail
                        Template:       bug/templates/showit.yaml
                        DocumentIndex:  0
                        ValuesIndex:    0
                        Path:   showit
                        Expected to equal:
                                bug-0.0.0
                        Actual:
                                bug-0.1.0
                        Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1,2 @@
                                -bug-0.0.0
                                +bug-0.1.0


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshot:    0 passed, 0 total
Time:        3.790639ms

Error: plugin "unittest" exited with error
```

**Expected behavior**

Successful tests as with unittest 0.7:
```
### Chart [ bug ] bug

 PASS  regression tests bug/tests/showit_test.yaml

Charts:      1 passed, 1 total
Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshot:    0 passed, 0 total
Time:        1.545077ms
```

**Desktop (please complete the following information):**
 - OS: Windows WSL 2 -> Ubuntu 24.04
 - Plugin Version : 0.8.0
