### ISSUE TITLE
Release.Namespace from suite not rendering.

### ISSUE THREAD

**Issue by P-Louw** [helm-unittest/helm-unittest#650]
**Bug**
When setting namespace at suite or test level it is not passed to the actual template.

**How to reproduce**
Rendering a S3 bucket from a template passing down the Release.Namespace works however unittest fails.

cnpg_cluster.yaml with ... to show abbreviated sections.
```yaml
{{- $rootAndCluster := ( dict "root" $ "cluster" $cluster "name" $name "release" $.Release ) }}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
...
...
spec:
  {{- include "department-provisioning.cluster.backup" $rootAndCluster | nindent 2 }}
```
_backup.tpl that defines the backup template and uses namespace to build s3 field.
```yaml
...
 destinationPath: "s3://{{ required "You need to provide the name of an S3 bucket that is dedicated to backups" .root.Values.s3.bucketName }}/department-pg/{{ .root.Release.Namespace }}"
...
```

The unittest that sets a namespace value and checks for it.
```yaml
suite: Restore
values:
  - ./single_basic_cluster_values.yaml
set:
  s3:
    endpointURL: "https://my-s3-server.domain.tld:9000"
    bucketName: chp-dba-otaint
    credentials:
      accessKeyId:
        name: s3-backup-credentials-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: s3-backup-credentials-secret
        key: ACCESS_SECRET_KEY
  clusters:
    test:
      spec:
        restorePITR:
          targetTime: "2025-03-24 21:00:00+01:00"
          origClusterName: department-orig
          automaticallySelectVolumeSnapshot: false
tests:
  - template: ../templates/cnpg-cluster.yaml
    it: Should have an externalClusters entry pointing to the barman object store to restore from
    release:
      namespace: test-namespace
    asserts:
      - contains:
          path: spec.externalClusters
          content:
            name: department-orig
            barmanObjectStore:
              endpointURL: "https://my-s3-server.domain.tld:9000"
              destinationPath: "s3://chp-dba/department-pg/test-namespace"
              s3Credentials:
                accessKeyId:
                  key: ACCESS_KEY_ID
                  name: s3-backup-credentials-secret
                secretAccessKey:
                  key: ACCESS_SECRET_KEY
                  name: s3-backup-credentials-secret
```
**Expected behaviour**
`destinationPath: "s3://chp-dba-otaint/department-pg/test-namespace"`
should be rendered in the test however it renders.
``destinationPath: "s3://chp-dba-otaint/department-pg/"``
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux fedora 41
 - Plugin Version 0.7.3
