### ISSUE TITLE
`failedTemplate` fails with `NOTES.txt` – ignores stderr content and compares raw output without any reason

### ISSUE THREAD

**Issue by JuryA** [helm-unittest/helm-unittest#652]
## Describe the bug

When using the `failedTemplate` assertion on `templates/NOTES.txt` in `helm-unittest`, the test fails even if the expected and actual error messages match.  
> This occurs due to overly complex internal logic that modifies the `stderr` output, conflating it with `stdout`, which is irrelevant in this context. It also attempts to distinguish between “raw” and “non-raw” strings and applies unnecessary special handling valid only for `NOTES.txt`.

**As a result, even a correct test will fail under normal conditions.**

## To Reproduce

1. Create a Helm chart containing a `templates/NOTES.txt` file with content:

  ```go
  {{- if and (hasKey $.Values "__test") (($__test := index $.Values "__test") | empty | not) -}}
  {{- tpl $__test $ -}}
  {{- end -}}
  ```
2. Write a unit test using the `failedTemplate` assertion with either `errorMessage` or `errorPattern`:

```yaml
suite: 'tests for `failedTemplate` assertions'
templates:
  - NOTES.txt
tests:
  - it: should pass
    set:
      __test: |
        {{ fail "some: text" }}
    asserts:
      - failedTemplate:
          errorMessage: "some: text"
```

3. Run `helm unittest`.

   **Result:**

![Image](https://github.com/user-attachments/assets/bdfa1c4c-612c-4e9e-a9d6-f4167a5f7a80)

4. Rename the file from `NOTES.txt` to `NOTES.tpl` (without changing its content).
5. Run the test again.

   **Result:**
   The test passes.

![Image](https://github.com/user-attachments/assets/c7e72424-7fb7-4a1b-9919-cb65774c0683)

## Expected behavior

The `failedTemplate` assertion should:

* **Not** apply any special logic for `NOTES.txt`;
* **Not** trim or re-parse other output than error message (the `stderr`);
* Simply compare the full error message (or a matching part via regex) **AS-IS**.

## Screenshots

**N/A** — see error output in reproduction steps.

## Desktop

* OS: Linux
* Plugin Version: `0.8.1`

## Additional context

> This issue complicates making negative test cases, as `NOTES.txt` is commonly used in Helm charts.
> The problem stems from fragile and unnecessary “helper logic” that *magically* modifies content and introduces nitty-gritty special-case handling.
> Stripping away these layers and comparing the error output directly would lead to a simpler and far more maintainable implementation.
> This is part of a broader pattern: multiple “smart” conveniences in the codebase actually end up undermining readability and reliability.
> A cleaner, more direct approach would go a long way in improving long-term maintainability.

**Comment by JuryA** [comment]
Relates to #183

**Comment by bebosudo** [comment]
As a workaround, I used `errorPattern` with `.*` before and after the string instead:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: test NOTES validation
templates:
  - ../templates/NOTES.txt
tests:
  - it: should fail when redis.host is not defined
    set:
      redis:
        host: ""
    asserts:
      - failedTemplate:
          errorPattern: ".*Redis host must be defined in 'redis.host'.*"
```

when using `errorMessage` I was getting
```
 FAIL  test NOTES validation	charts/xxx/tests/notes_test.yaml
	- should fail when redis.host is not defined

		- asserts[0] `failedTemplate` fail
			Template:	xxx/charts/xxx/templates/NOTES.txt
			DocumentIndex:	0
			Expected to equal:
				Redis host must be defined in 'redis.host'.
			Actual:
				raw: Redis host must be defined in 'redis.host'.
```
