### ISSUE TITLE
notContainsDocument request

### ISSUE THREAD

**Issue by timothyclarke** [helm-unittest/helm-unittest#669]
**Is your feature request related to a problem? Please describe.**
I think it's a feature request. 
I need to write tests for an existing chart before possibly making changes. 

- The chart has a number of multi document yaml templates.
- Some of the yaml documents within the template are conditional eg `{{ if .Values.key.subkey }}`

**Describe the solution you'd like**
I would like to be able to test that a document does not exist when rendering a template. 

**Describe alternatives you've considered**
I have tried 
* `containsDocument` && `asserts[0].hasDocuments.clound: 0` (This fails because the document is not there)
eg
```
tests: 
  - it: should NOT have the unwanted document
    documentSelector:
      path: metadata.name
      value: unwanted-document
    asserts:
      - hasDocuments:
          count: 0
          filterAware: true
```
* `notContains` - This fails because there are other documents with `metadata.name` (they have different names, I cannot seem to create a test for "so long as this name is not in the list" as well as other documents of the same `kind` 
eg 
```
  - it: should NOT have the unwanted document
    asserts:
     - notContains:
         path: metadata.name
         content: unwanted-document  
```
I've also tried 
```
     - notContains:
         path: metadata
         content: 
            name: unwanted-document  
```

Assuming the template is
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wanted
data:
  key: value

{{ if .Values.key.subkey }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unwanted-document
data:
  key: value
{{- end }}
```

**Additional context**
