### ISSUE TITLE
Additional _helper.tpl for a test suite.

### ISSUE THREAD

**Issue by timothyclarke** [helm-unittest/helm-unittest#679]
I am aware of https://github.com/helm-unittest/helm-unittest/issues/288 but I think this one is different.

**Is your feature request related to a problem? Please describe.**
I would like a way of creating a custom helper / definition for a test suite

I am writing a library to be consumed by multiple charts within my org. The library needs to create an AWS IAM policy statement for use with crossplane as there are certain standards.  Library functions can be redefined in an application chart, so this gives me a way to create a consistent way to feed data back to the library to do it's thing. 
The issue then comes to unittesting. How do I test with a definition coming from the library and as a separate test (or test suite) redefine the definition as I would expect the app chart writers to do

**Describe the solution you'd like**
I'd like the ability to have inline files within a test suite that is added to the chart immediately prior to running the test
eg
```
---
suite: Additional helper test
additional_template: |-
  {{- define "mylib.name" -}}
  myLibName
  {{- end }}
templates:
 - deployent.yaml
release:
  name: testing
tests:
  - it: should use the custom name definition rather than the standard one
  asserts:
    - equal:
        path: metadata.name
        value: myLibName
```

**Describe alternatives you've considered**
I'm already writing the CI so the test suites are application charts that consume the library charts. Having multiple app charts wouldn't scale

I've considered passing this as a dictionary, but then it becomes harder to use the library (and educate other teams on how to make use of it)

**Additional context**
My Library look something like the following (`templates/_library.tpl`)
```
{{- define "library.iam" }}
Sid: s3Bucket
Effect: Allow
{{- end }}

{{- define "library.replaceMe" }}
elements: []
{{- end }}

{{- define "library.policy-statement" -}}
{{- $elements := list -}}
{{- $elements := append $elements (include "lib-s3.iam" . | fromYaml) }}
{{- range $additional := ( include "replaceMe" . | fromYaml ).elements }}
  {{- elements = append $elements $additional }}
{{- end }}
Version: 2012-10-17
Statement: {{ $elements | compact | toPrettyJson |nindent 2 -}}
{{- end }}
```

Then in the application chart my `templates/_custom.tpl` would include 
```
{{- define "application.additional-one" }}
Sid: firstAdditional
Effect: Allow
{{- end }}

{{- define "application.additional-two }}
Sid: secondAdditional
Effect: Allow
{{- end }}

{{- define "application.additional-policies" -}}
{{- $elements := list -}}
{{- $elements := append $elements (include "application.additional-one" . | fromYaml) }}
{{- $elements := append $elements (include "application.additional-two" . | fromYaml) }}
{{- $elements | toJson }}
{{- end }}

{{- define "library.replaceMe" }}
elements: {{ include "application.additional-policies" }}
{{- end }}
```
Note that the `library.replaceMe` definition in the application chart replaces the `library.replaceMe` definition in the library.

Finally the application charts `templates/iam.yaml` might be
```
{{- include "library.policy-statement" . }}
```

which would then render 
```
Version: 2012-10-17
Statement: [
    {
      "Sid": "s3Bucket",
      "Effect": "Allow"
    },
    {
      "Sid": "firstAdditional",
      "Effect": "Allow"
    },
    {
      "Sid": "secondAdditional",
      "Effect": "Allow"
    }
  ]
```
The yaml docs have been simplified. My issue is writing unittests with and without the additional  `templates/_custom.tpl`

Part of the complexity (reason for not using a dictionary) is that the above needs to go into the next definition to create the valid yaml for k8s / crossplane
```
{{- define "library.iamPolicy" }}
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
spec:
  forProvider:
    document: | {{ include "library.policy-statement" . | fromYaml | toPrettyJson | nindent 6 }}
{{- end }}
```

Application charts are doing `{{- include "library.iamPolicy" . }}` rather than `include "library.policy-statement" . }}`
